### ISSUE TITLE
Importing empty measures.

### ISSUE THREAD

**Issue by Canaanabolaanan** [powertab/powertabeditor#154]
This is probably a good thing, but it imports empty measures ... correctly. In PTE1.7, an empty measure is skipped as it is played, in terms of the MIDI. If there's no rest or notes, there's no content, and the MIDI doesn't acknowledge its existence. So on occasion, I would use empty measures to separate passages to remind myself they weren't completed as I was writing. But importing and playing them in 2.0, they get counted as measures of rest and throw off the timing of the song as it was saved (bass score vs. guitar score, for example). 

Of the two styles, I don't know that any one is more correct for something like this. But at the very least, it's good to know how this operates to explain where some differences between bass/guitar scores come from. 

What do you guys think? Should this be the preferred way to handle importing empty measures/systems? 

I'm also wondering if stuff like this should go in the Wiki, or a tutorial. There was another behavior I came across the other day where I had a similar thought, to publicly express how a certain quirk is handled, in cases where it might be a matter of preference with no right/wrong way to address it. Currently I can't recall what it was... >:(

**Comment by cameronwhite** [comment]
I've changed the importer to skip empty measures, since the "measure" between adjacent repeat end and repeat start bars causes odd behaviour when expanding or merging repeats from the guitar and bass scores.
