### ISSUE TITLE
Repeating signs

### ISSUE THREAD

**Issue by ghost** [powertab/powertabeditor#158]
I have a .gp5 file with a section that should be repeated. The last measure differs for the first and second repeat. When playing the song however, it doesn't repeat at all. I have .ptb files too with thesame situation which works correctly.
Thesame file also has a situation with a section that should be repeated in a regular way, but it ends in a loop and repeats itself too many times.

**Comment by cameronwhite** [comment]
I think I'll close this as a duplicate of #63, but if you have a file to reproduce it with that would be helpful!
