### ISSUE TITLE
Renaming "Player"

### ISSUE THREAD

**Issue by theczar** [powertab/powertabeditor#161]
Is it (could it be) possible to rename the Players? If one would prefer e.g. Gtr I, Gtr II… in the tab instead of Player 1 etc.

**Comment by cameronwhite** [comment]
Clicking on the player's name in the mixer allows you to edit it, but perhaps the player changes in the score should display the player's name instead of the player number.

**Comment by theczar** [comment]
Yeah, renaming in the mixer works. What I was after is that the score name would reflect the name that is in the mixer, so it would be same in both. Or maybe could be an option in the preferences? "Player names in score follow the mixer names" or something :) I have no idea how easy/difficult that kind of optional behavior is to implement in code though.

**Comment by cameronwhite** [comment]
I think that's probably what the default behaviour should be, rather than making it optional.
