### ISSUE TITLE
Copy/paste issues

### ISSUE THREAD

**Issue by theczar** [powertab/powertabeditor#167]
Older PT 1.7 files seem to break the copy command. When opening an old file it doesn't work and the edit menu won't even flash when hitting Cmd+C.

When creating a new file, it works fine. But if I even open an old file, do nothing with it and close it, and create a new file, copy has stopped working. I have to restart the editor to make it work again.

**Comment by cameronwhite** [comment]
Seems to work fine for me, but it could be something OSX-specific.

**Comment by cameronwhite** [comment]
Similar to #162, closing as unable to reproduce
