### ISSUE TITLE
Build Error in Windows with QT 5.4

### ISSUE THREAD

**Issue by develoken** [powertab/powertabeditor#171]
I'm not sure if I'm doing something wrong but I am unable to build the code in Windows.
I am using
Boost 1.57
zlib 1.2.8
QT 5.4
Visual Studio 2013 Express

CMake throws bunch of warnings like below but it does finish successfully:

CMake Warning (dev) in source/CMakeLists.txt:
  Policy CMP0020 is not set: Automatically link Qt executables to qtmain
  target on Windows.  Run "cmake --help-policy CMP0020" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

Then, when I try to build it with Visual Studio, it throws few errors that seems to be related to QT:
Error	1	error C2664: 'void QComboBox::addItems(const QStringList &)' : cannot convert argument 1 from 'initializer-list' to 'const QStringList &'	C:\Users\ken\Documents\GitHub\powertabeditor\source\dialogs\benddialog.cpp	32	1	ptedialogs

I also tried QT 5.3 and get the same error. I haven't tried QT 5.2 as msvc2013 was not available to download.

**Comment by cameronwhite** [comment]
From those error messages, it sounds like the initializer list constructor for QStringList is unavailable - maybe https://bugreports.qt.io/browse/QTBUG-39142 is what you're running into? (I'm using Qt 5.2 on my Windows build, compiled manually with the README instructions, so I haven't hit this myself)

Can you try adding `add_definitions(-DQ_COMPILER_INITIALIZER_LISTS)` to Windows section of the root CMakeLists.txt file and see if that fixes your build?

**Comment by develoken** [comment]
Adding add_definitions(-DQ_COMPILER_INITIALIZER_LISTS) to the root CMakeList.txt fixed the original error.

However, it throws another error at the post build step:
Error	1	error MSB3073: The command "setlocal
"C:\Program Files (x86)\CMake\bin\cmake.exe" -E make_directory C:/Users/ken/Documents/GitHub/powertabeditor/build/bin/platforms
if %errorlevel% neq 0 goto :cmEnd
"C:\Program Files (x86)\CMake\bin\cmake.exe" -E copy D:/QT/5.4/msvc2013_64/lib/cmake/Qt5Core/../../../lib/Qt5Widgetsd.dll C:/Users/ken/Documents/GitHub/powertabeditor/build/bin
if %errorlevel% neq 0 goto :cmEnd
.......
:VCEnd" exited with code 1.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	132	5	powertabeditor

I was able to fix this by copying missing files from D:\QT\5.4\msvc2013_64\bin to D:\QT\5.4\msvc2013_64\lib
I guess this is because I downloaded the prebuilt QT instead of building on my own?

Anyways, I was able to build it successfully in the end.
Thanks!

**Comment by develoken** [comment]
Another issue found:
I was able to build but when I tried to run it I got an error saying icuin53.dll is missing.
I was able to fix it by copying the missing files(icuuc53.dll, icuin53.dll, icudt53.dll)from D:\QT\5.4\msvc2013_64\lib

**Comment by cameronwhite** [comment]
I guess this can be closed now that #172 is merged in.
