### ISSUE TITLE
Can't install new update

### ISSUE THREAD

**Issue by NejiHyuga900** [powertab/powertabeditor#174]
I still have Power Tab Editor 2.0 Alpha 6 and for some reason, I cannot install Alpha 7 and I also try re-installing Alpha 6 but it doesn't work either. While installing, I keep getting this message: "The feature you are trying to use is on a network resource that is unavailable. Click OK to try again, or enter an alternate path to a folder containing the installation package 'powertabeditor.msi' in the box below." I found powertabeditor.msi somewhere within my ProgramData Package Cache (I have one for Alpha6 and one for Alpha7 was created in a different folder) but it didn't work. I even created the folder that the  Use source was set to by default. When I press OK after selecting either powertabeditor.msi that are on my computer, it says "The file 'C:\ProgramData\Package\Cache\[any folder that I have powertabeditor.msi in]' is not a valid installation package for the product Power Tab Editor. Try to find the installation package 'powertabeditor.msi' in a folder from which you can install Power Tab Editor." I don't know why it isn't working. Then when I cancel the installation, it says "The older version of Power Tab Editor cannot be removed. Contact your technical support group."
![capture](https://cloud.githubusercontent.com/assets/6454220/7339021/e6d71b76-ec2d-11e4-81c4-81db9eb79e7f.PNG)

After cancellation, I then get a Setup Failed message during the Setup, which says "0x80070643 - Fatal error during installation" with a log file, which I will post as an image.
![capture1](https://cloud.githubusercontent.com/assets/6454220/7339052/d008c772-ec2e-11e4-8eba-484a35b04793.PNG)

**Comment by cameronwhite** [comment]
I really have no idea what's going wrong. The most promising thing I found from some googling is https://support.microsoft.com/en-us/mats/program_install_and_uninstall - can you give that a try?

**Comment by NejiHyuga900** [comment]
Thank you! That program fixed the problem and now I'm able to install the new update.

**Comment by cameronwhite** [comment]
Great! Glad to hear it worked!
