### ISSUE TITLE
Note/rest duration issues

### ISSUE THREAD

**Issue by theczar** [powertab/powertabeditor#175]
Don't know if this is a feature, but to me there seems to be some odd behavior regarding the note durations and how you set them. And this is on MacOS 10.8.5., don't know about others.

If I have selected a note duration from the Notes menu (let's say a quarter note) and then edit some note durations on the tab using the key command Shift + Arrow Up/Down, then this change of duration will affect only the notes I'm editing, the sort of "master" note value will stay at quarter note. So if I change a bunch of notes to sixteenth notes I cannot immediately go on and continue entering new sixteenth notes, but I have to go to the Notes menu to change the duration.

However, this occurs only if I'm using Shift + Arrow Up/Down on the notes. If I go to an empty slot on the tab, where there are no notes and use the key commands to change the value, it will change it and I can enter notes with new duration. Still, the duration change is not reflected in the Notes menu immediately, it shows up only after I've entered a note.

Similar thing happens with the rests too. Whatever note I have on the tab and I want to change it to a rest, it will always change to a rest with the duration that is set in the Notes menu, not to the same duration value as the note, which I believe should be the default behavior.

Hope this explanation makes some sense.

**Comment by cameronwhite** [comment]
I think the behavior of Shift + Up/Down was intentional - if you select a group of notes (which could have varying durations), then there isn't a sensible choice for what the new active duration should be set to.

**Comment by cameronwhite** [comment]
See also #70

**Comment by cameronwhite** [comment]
Fixed along with #70.
