### ISSUE TITLE
TREND MICRO OfficeScan detects a VIRUS/MALWARE when trying to install

### ISSUE THREAD

**Issue by marklaszlo** [powertab/powertabeditor#176]
Security Threat is TROJ_FAKEAV and won't install.
http://www.trendmicro.com/vinfo/us/threat-encyclopedia/malware/TROJ_FAKEAV.BMC

**Comment by cameronwhite** [comment]
Sounds like a false positive - the installer certainly does not install a trojan or edit the registry key mentioned in that link (see https://github.com/powertab/powertabeditor/tree/master/windows for the installer's source code)
