### ISSUE TITLE
QObject::setParent: Cannot set parent, new parent is in a different thread

### ISSUE THREAD

**Issue by rekado** [powertab/powertabeditor#183]
When attempting to open one of my original Powertab 1.7 files I get this error before anything is rendered:

~~~
Opening file:  "/home/rekado/audio/ptb/ToaoM/april.ptb"
File loaded in 39 ms
Tab creation started ...
Using 1 worker thread(s)
QObject::setParent: Cannot set parent, new parent is in a different thread
~~~

I built the latest version from master in Debug mode.  When compiled with release mode powertabeditor dies with SIGABRT.  This only happens with this one file as far as I can tell.

**Comment by cameronwhite** [comment]
If it only occurs with a specific file, would you be able to provide a link to it?

**Comment by rekado** [comment]
I sent you an email containing the file.
