### ISSUE TITLE
Stop playback feature.

### ISSUE THREAD

**Issue by blackfox13** [powertab/powertabeditor#185]
While I do love the pause and continue playback feature in 2.0, in 1.7 you were able to stop then playback from wherever you left the cursor. 2.0 doesn't seem to have a 'stop' function; only a pause which means I have to constantly scroll back to where I want it to start from again. Can a stop button similar to 1.7 be added please?

**Comment by moppius** [comment]
The stop button is good but sometimes doesn't seem to register clicks. Occasionally I've had to click on it 4-5 times before it will even stop. I haven't had any luck tracking this down yet, with a debugger attached it looks like the command doesn't even fire via Qt :(
