### ISSUE TITLE
Marking

### ISSUE THREAD

**Issue by Dk-felix** [powertab/powertabeditor#186]
I would like the possibility of marking a complete score or multiple staff at once.

**Comment by cameronwhite** [comment]
What do you mean by "marking" a score?

**Comment by Dk-felix** [comment]
What I wrote.

**Comment by cameronwhite** [comment]
Sorry, you'll need to provide more details about what you're actually requesting if you want me to be able to implement this. I don't know what you mean by marking, since that's not a term I've seen used with respect to tablature.

**Comment by Dk-felix** [comment]
Who cares?
