### ISSUE TITLE
Text feature

### ISSUE THREAD

**Issue by Dk-felix** [powertab/powertabeditor#187]
I would like  a text feature - it should be possible to mark the text along with marking the staff itself, too.

**Comment by cameronwhite** [comment]
Can you explain more about what it is you're actually requesting, and how it differs from the existing text feature?

**Comment by Dk-felix** [comment]
No, I don't think so.

**Comment by cameronwhite** [comment]
If you can't provide any more information, then there's nothing I can do here.
