### ISSUE TITLE
Stop clicking from stealing focus.

### ISSUE THREAD

**Issue by cinereous** [powertab/powertabeditor#191]
Clicking to add notes automatically shifts the current section to the top of the screen; this is insanely annoying, as it shifts the previous section completely off the screen, making it impossible to see the previous section.

**Comment by DontBelieveMe** [comment]
@cameronwhite Does this block of code do anything other than offset the section? It seems too deliberate to be a bug.  
![capture](https://cloud.githubusercontent.com/assets/10855194/11326245/9fb5245c-915c-11e5-986f-8b455a5c7acf.PNG)

**Comment by cameronwhite** [comment]
@DontBelieveMe It's computing what the height of the preceding staves in the current system are (skipping over any hidden staves), for cases where the caret is not in the first staff of the system. Are there issues with it?

**Comment by DontBelieveMe** [comment]
Was there a particular reason for implementing this (and moving the stave that the carets in to the top), as it is quite irritating and disorienting when clicking to add notes (as described in this issue)

**Comment by cameronwhite** [comment]
I don't think that code is actually contributing to this issue - redrawing the caret is separate from choosing which area of the canvas to display (which is done by `ScoreArea::adjustScroll()`). During MIDI playback the caret is moved around, and so the viewport also needs to be adjusted to keep the current system visible. Perhaps that method should only scroll the canvas during MIDI playback, rather than all the time?

**Comment by DontBelieveMe** [comment]
Yeah that sounds like a better idea. Perhaps it should be an option or a setting?

**Comment by cameronwhite** [comment]
I'm not sure if a setting is needed. It might just be that auto-scrolling needs to be disabled if MIDI playback is off and the current system is in view? If the user clicks somewhere, the canvas shouldn't scroll at all, but if they press Page Down a bunch of times then it should scroll along.

**Comment by DontBelieveMe** [comment]
scrolling be controlled by the mouse (I.e. click and drag) or is this not consistent?

**Comment by cameronwhite** [comment]
Not quite sure if I understand what you meant, but clicking and dragging to scroll in a touchscreen-style way would be a totally separate feature to discuss.
Currently, I think if the user clicks somewhere (e.g. in a different staff/system), no scrolling should happen. If they scroll with the mouse wheel and that causes the caret to disappear off screen, then that's fine.
