### ISSUE TITLE
Tests fail on ARM

### ISSUE THREAD

**Issue by rekado** [powertab/powertabeditor#195]
We're building the latest release of powertabeditor on the GNU Guix build farm, which includes armhf build slaves.  Unfortunately, the tests do not pass on armhf:

```
...
-------------------------------------------------------------------------------
Actions/EditStaff
-------------------------------------------------------------------------------
/tmp/nix-build-powertabeditor-2.0.0-alpha8.drv-0/powertabeditor-2.0.0-alpha8/test/actions/test_editstaff.cpp:25
...............................................................................

/tmp/nix-build-powertabeditor-2.0.0-alpha8.drv-0/powertabeditor-2.0.0-alpha8/test/actions/test_editstaff.cpp:25: FAILED:
due to unexpected exception with message:
  Parse error at offset 4294967295: The document root must not follow by other
  values.
...
```

The failures look all the same.  Each time it's a parse error at offset `2^32-1`.  Does this indicate overflow?

The full build output can be seen here:
http://hydra.gnu.org/build/762896/log/raw

**Comment by cameronwhite** [comment]
It seems like something is going wrong with JSON parsing (via RapidJSON). According to its docs, that error message should occur if there are more characters after parsing a complete JSON object. I'm not sure where that would come from.

**Comment by cameronwhite** [comment]
I think this was probably fixed by https://github.com/powertab/powertabeditor/commit/d8575e6b7acf4c683f9859272fb014b45e05c925 - I recall seeing error messages similar to that.
