### ISSUE TITLE
MSVCP140.DLL is missing error after installing alpha 9

### ISSUE THREAD

**Issue by smokewood** [powertab/powertabeditor#197]
I uninstalled alpha 8 and deleted the powertab folder.
Reboot my system (win10 pro 64bit)
Then downloaded and installed alpha 9

Closed the installer and launched from the start menu:
System error:
The program can't start because MSVCP140.dll is missing from your computer. Try reinstalling the program to fix this problem.
Click ok

System error:
The program can't start because VCRUNTIME140.dll is missing from your computer. Try reinstalling the program to fix this problem.
click ok

Then the whole thing repeats:
System error:
The program can't start because MSVCP140.dll is missing from your computer. Try reinstalling the program to fix this problem.
Click ok

System error:
The program can't start because VCRUNTIME140.dll is missing from your computer. Try reinstalling the program to fix this problem.
click ok
window closes

I did reinstall bur got same errors.

**Comment by cameronwhite** [comment]
Does the 32-bit installer work? It sounds like there may be a bug with installing the 64-bit runtime (https://connect.microsoft.com/VisualStudio/feedback/details/1746644/microsoft-vc140-crt-x64-msm-merge-module-installs-c-c-runtime-dlls-in-x32-folder)

**Comment by smokewood** [comment]
I would just like to add to my OP that I had updated to windows 10's latest version about a week ago.
Alpha 8 was still working though after the update.
Have not been able to load alpha 9 at all.

**Comment by cameronwhite** [comment]
I've uploaded an updated version of the 64-bit installer. Please give it a try and re-open the issue if it does not work (be sure to uninstall the old alpha 9 installer first).
