### ISSUE TITLE
This application failed to start because it could not find or load the Qt platform plugin "windows".

### ISSUE THREAD

**Issue by NejiHyuga900** [powertab/powertabeditor#199]
I'm using Windows 10. After when I installed PTE 2.0 Alpha 9, I was getting some DLL error messages that was missing some DLL files that were in the Alpha 8 update, so I uninstalled Alpha 9, re-installed Alpha 8 to copy the non-Qt DLL files, uninstall Alpha 8 with the DLL files back-upped, and re-installed Alpha 9, and placed the Alpha 8's DLLs to fix those DLL error messages.

But then, when I try to open it up with all the required DLLs, I get the message: "This application failed to start because it could not find or load the Qt platform plugin 'windows'. Reinstalling the application may fix this problem." I tried re-installing Alpha 9 and still get the same message. I even tried uninstalling it and installing the older alpha releases but those give the same message. Power Tab Editor 2.0 did work when I was using Windows 7. Is it not compatible in Windows 10 or did I do something wrong? This is my first time trying to use Power Tab Editor v2.0 after I upgraded to Windows 10.

**Comment by cameronwhite** [comment]
Did you maybe hit the same issue as #197?
It sounds like something may have been messed up with your upgrading and downgrading - the latest build (which switched from Qt 5.4 to 5.6) shouldn't rely on  `platforms/qwindows.dll` any more (verified with DependencyWalker). If you right-click and go to Properties/Details, what version are the Qt dlls?

**Comment by NejiHyuga900** [comment]
The Qt DLLs I have in the base folder says version 5.6.0.0, but qwindows.dll in platforms folder says version 5.4.1.0. Still get the same message even if I keep qwindows.dll or toss it out the platforms folder

**Comment by cameronwhite** [comment]
Hmm, it sounds like something went wrong with the upgrade of the main .exe. It should depend on the vc140-mt-1_59 dlls. I'll see if I can reproduce this on my machine.

**Comment by cameronwhite** [comment]
On my machine (Windows 10 as well), upgrading from alpha 8 to 9 worked okay. Were you on the 64-bit or 32-bit installer? And if you completely uninstall everything and just install alpha 9, which error do you get?

**Comment by NejiHyuga900** [comment]
I used a 64-bit installer, as I'm using Windows 10 64-bit. Okay, I just uninstalled Alpha 9 and deleted everything a associated with it that remained after uninstallation. After reinstalling it with nothing in its folder, I got no errors that it's missing Alpha 8's DLLs this time, indicating that it's now using the vc140-mt-1_59 dlls, but it still goes straight to the point where I get the Qt plugin 'windows' error. Also, no platforms folder with qtwindows.dll was generated when I reinstalled Alpha 9 after deleting everything from that folder (or did that platforms folder came from a different alpha release?).

I then installed the Alpha 9 32-bit version and I'm getting a different message with the 32-bit version: "The application was unable to start correctly (0xc000007b). Click OK to close the application." And that one doesn't have a platforms folder with qtwindows.dll either.

**Comment by hymerman** [comment]
I get this error on startup too. I've not had PTE installed before; I just installed the Alpha 9 win64 release for the first time.

I'm on Windows 7, and I'm not sure if it's relevant but it's a machine that's been used for C++ development for years so likely has one of every C++ runtime DLL somewhere :)

**Comment by cameronwhite** [comment]
I've uploaded an updated version of the 64-bit installer. Please give it a try and re-open the issue if it does not work (be sure to uninstall the old alpha 9 installer first).

**Comment by NejiHyuga900** [comment]
It's working now. Thanks.

**Comment by hymerman** [comment]
Works here too - thank you!

**Comment by Canaanabolaanan** [comment]
Is the 32-bit installer going to be corrected as well? I've also had the "The application was unable to start correctly (0xc000007b). Click OK to close the application."  message. The 64 bit installer at least opens. It runs, but there are some strange playback issues going on- different tempos than written, note durations not lasting more than an 8th note,  - I'm not sure what else yet.

**Comment by cameronwhite** [comment]
Sorry, yeah, I'll try to put together an updated 32-bit build

**Comment by cameronwhite** [comment]
I've uploaded a new 32-bit installer - let me know if that works okay for you.

**Comment by Canaanabolaanan** [comment]
So far, it's not. I've uninstalled and reinstalled it to make sure. Now I get this message:
![alpha 9 crash](https://cloud.githubusercontent.com/assets/8230669/11455199/586cb5ac-961f-11e5-9570-110391a98827.png)

Also, when I choose custom install and select a different directory, it ignores that and installs it in the default spot anyway: C:\Program Files (x86)\Power Tab\Power Tab Editor

I feel like the \Power Tab\ directory is unnecessary and try cutting that out of there. Doesn't work. Plus the "Launch" button is broken. I wonder if this is all related, or should I post issues for them?

**Comment by cameronwhite** [comment]
Probably all related - if  you manually install https://www.microsoft.com/en-ca/download/details.aspx?id=48145 (x86) version, does it launch?

**Comment by Canaanabolaanan** [comment]
Yes, that gets it to launch, but all the other issues remain - launch button, tempo, duration, install location.

**Comment by cameronwhite** [comment]
ok, then I'd say file separate issues for those.
