### ISSUE TITLE
The ability to remove rests. 

### ISSUE THREAD

**Issue by DontBelieveMe** [powertab/powertabeditor#202]
Currently rests cannot be deleted or removed meaning that it you want to remove them they have to be swapped for a note and then removed. This is a pain.  

**Edit**: Set `Delete` to Operate on Rests.

**Comment by cameronwhite** [comment]
`Ctrl+Delete` works, since a rest is a `Position` and doesn't have any `Note's` (which is what `Delete` operates on). But it would definitely be sensible to just make Delete work in the expected way for rests.

**Comment by DontBelieveMe** [comment]
Should the ```Ctrl+Delete``` Behavior be kept for rests? This might keep deleting them consistent with other Positions. Or would it be easier to unify ```Position```'s and ```Note```'s to just use ```Delete```?

**Comment by cameronwhite** [comment]
A `Position` is a container of `Notes`, so you need to have the ability to either delete all of the notes (which is effectively what `Ctrl+Delete` does) or delete individual notes. I think allowing either `Ctrl+Delete` or `Delete` for rests is fine.

**Comment by DontBelieveMe** [comment]
This links to #220
