### ISSUE TITLE
Opening Multiple files

### ISSUE THREAD

**Issue by DontBelieveMe** [powertab/powertabeditor#203]
As in selecting multiple files in the windows explorer. The only potential problem with this is that opening/loading one file isn't the fastest and my initial tests show opening more than one document/file takes quite a long time.

**Comment by cameronwhite** [comment]
Are you testing on a debug build? On Windows they're quite slow

**Comment by DontBelieveMe** [comment]
I've tested it on a release build now - it's a bit better, but still very slow.

**Comment by cameronwhite** [comment]
It doesn't seem too slow for me opening a single file - do you have a branch with the changes you're testing with?

**Comment by DontBelieveMe** [comment]
Yes - branch "Issue-203" at DontBelieveMe/powertabeditor.
It is especially slow when loading more than 2 - 3 files. At times it has taken a few seconds!

**Comment by cameronwhite** [comment]
In my test it took me about 2.5 - 3 seconds to open 18 fairly large v1.7 tabs, which isn't too bad. One potential improvement might be to delay rendering a score until the tab is switched to, since my guess is that's probably taking up most of the time.

Loading the files could probably be multithreaded as well, but there may be a couple thread safety issues to fix (e.g. if an error message is displayed, that needs to happen on the main (GUI) thread).

**Comment by DontBelieveMe** [comment]
When opening 18 moderately small files (most of them being 1KB) (v1.7)  it took an average of 21 seconds. Also after loading all of them the where some weird graphical glitches. 

Would is be possible just to have the appearance of having files open. As in if there are files which are off the tab widget thing, or not often opened then just displaying the tab widget and opening the file if it is clicked.

![capture](https://cloud.githubusercontent.com/assets/10855194/11453293/3024e082-95fd-11e5-860b-8942807350d4.PNG)
(Tabs that are not displayed on the tab widget displayer thing - the arrow keys)

**Comment by cameronwhite** [comment]
Hmm, that sounds surprisingly slow for a release build (but about what I might expect for a debug build).

Yeah, that's sort of what I meant by delaying the rendering of a score, but I suppose loading the score from the file could also be delayed until the tab is opened.

**Comment by cameronwhite** [comment]
Closing invalid issues - this can be revisited if multi-file opening is implemented
