### ISSUE TITLE
Alpha 9, Bends don't sound like bends anymore.

### ISSUE THREAD

**Issue by smokewood** [powertab/powertabeditor#205]
Downloaded the latest alpha 9 64 bit version.

Notes that are bent, don't sound bent and they are not changing the pitch.
Example would be 13th fret not bent sounds the same as 13th fret with a full step bend applied to it.

Hope that is clear...

Thanks

**Comment by cameronwhite** [comment]
Hmm, the bends sound okay for me. If you could post a file, that might be useful just in case there are slight differences versus what I set up.
Has anyone else run into this?

**Comment by smokewood** [comment]
It seems as if I create a new score the bends sound fine, however the few tabs I have left over from version 1.7 don't seem to be working. The bends don't change pitch.

Any way to send you one?

**Comment by cameronwhite** [comment]
Sure - my email should be on my Github profile page

**Comment by cameronwhite** [comment]
Closing issues with missing information
