### ISSUE TITLE
New Feature Request - Screen Zoom

### ISSUE THREAD

**Issue by mssmith1972** [powertab/powertabeditor#211]
Would it be possible to add a Zoom feature under the Window menu.  I use larger monitors because of poor eyesight.  On a 24" monitor at 1920x1080 (system recommended) the score only uses about 40% of the screen.  At this size I have a hard time seeing things.  It would be great to have the ability to zoom in/out by percentage (100%, 150%, 200%, etc.) similar to MS Office products.

**Comment by cameronwhite** [comment]
Yeah, this would be really good to add. Shouldn't be too hard to implement - I think `QGraphicsView` or `QGraphicsScene` should have some scaling / transformation options.
