### ISSUE TITLE
Bulk Conversion Utility

### ISSUE THREAD

**Issue by mssmith1972** [powertab/powertabeditor#212]
I have ~15K tab files in .ptb format.  Has anyone created a bulk update utility to convert all .ptb files in a folder structure to .pt2?

**Comment by cameronwhite** [comment]
Not that I know of, but I don't think it would be too difficult to write a simple command line application using the `FileFormatManager` class.

Be aware that you may lose some information for features that aren't yet supported in v2.0, such as rhythm slashes, so I wouldn't delete your .ptb files

**Comment by psyomn** [comment]
Hi there, I'd like to tackle this. I'm not very proficient with C++ but I can give it a try. 

I was considering implementing this inside a dialog, within a "Tools" menu or the like. What do you think?

**Comment by cameronwhite** [comment]
That would be a great contribution!
I think it would work well as a dialog, maybe just under the `File` menu since it's dealing with saving and loading

**Comment by psyomn** [comment]
Cool! Will be fun to work on this!

**Comment by cameronwhite** [comment]
Great, feel free to let me know if you have any questions!
