### ISSUE TITLE
Issues With Scaling and playback

### ISSUE THREAD

**Issue by DontBelieveMe** [powertab/powertabeditor#213]
During playback (after scaling) the caret/playback bar thing will go out of view.
After scaling out (i.e 50%), the jumps (to keep the caret at the top of the screen), are too large and when scaling in (e.g 150%) the jumps are too small.

![infocus](https://cloud.githubusercontent.com/assets/10855194/13074338/d88e0564-d49b-11e5-857b-f0ba7cfeafb4.png)
Here the caret slowly moves to the bottom of the view.

![outfocus](https://cloud.githubusercontent.com/assets/10855194/13074345/e48534b4-d49b-11e5-958f-979c5a4fc373.png)
Here the caret is not visible at all

**Comment by cameronwhite** [comment]
Fixed by ef65bbb9
