### ISSUE TITLE
Failed to install packages on Debian Jessie

### ISSUE THREAD

**Issue by pchg** [powertab/powertabeditor#215]
Hello,
It seems that a number of needed packages are not available on a standard Debian stable (Jessie) installation:
```
  # root@durandeux: /home/pierre/dev/powertabeditor        < 2016_03_18__19_42_16 >
apt install cmake qtbase5-dev libboost-dev libboost-date-time-dev libboost-filesystem-dev libboost-iostreams-dev libboost-program-options-dev libboost-regex-dev libasound2-dev libiberty-dev binutils-dev rapidjson-dev libpugixml-dev, catch, librtmidi-dev
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet rapidjson-dev
E: Impossible de trouver le paquet libpugixml-dev,
E: Impossible de trouver le paquet catch,
```
(as you guessed, the three last error messages in French mean that it was impossible to find such and such packages)

When you mention in the README.md "These instructions assume a recent Ubuntu/Debian-based system," do you mean that Ubuntu is based on Debian, or that it should equally work with both distros?

**Comment by cameronwhite** [comment]
I think those packages were added pretty recently, so I guess they're not in Debian stable yet. Those libraries are actually optional - if they're not found on the system they're compiled from the submodules in the `external` directory instead of using the system libraries.

**Comment by jpleau** [comment]
Remove the periods from the command.. "catch," is not a package, "catch" is.
