### ISSUE TITLE
Are there drum scores?

### ISSUE THREAD

**Issue by theturboman** [powertab/powertabeditor#218]
In your repository, you said that drums score was already been included in Power Tab 2.0, but I don't see any drum score but only the guitar and basses.

**Comment by cameronwhite** [comment]
I'm not sure where it says that drum scores are supported, but they haven't been implemented yet. They're definitely planned for the future, though

**Comment by DontBelieveMe** [comment]
This is similar to #36

**Comment by cameronwhite** [comment]
yeah, I'll close this as a duplicate
