### ISSUE TITLE
Segmentation fault on first use

### ISSUE THREAD

**Issue by RobFog** [powertab/powertabeditor#230]
2.0.0-alpha9 on a mid-2009 13" MacBook Pro, OS X 10.11.6

Steps to reproduce:
- Download Guitar Pro tab from here: https://tabs.ultimate-guitar.com/b/beatsteaks/as_i_please_guitar_pro.htm
- In powertabeditor.app, open the file via File → Open…
- Please play.
→ Segmentation fault

Log attached.
[powertabeditor-crash.txt](https://github.com/powertab/powertabeditor/files/596111/powertabeditor-crash.txt)

**Comment by RobFog** [comment]
Same as #204?

**Comment by cameronwhite** [comment]
I think this is a separate issue - in the latest development build it still crashes, but the file in #204 has some looping issues
