### ISSUE TITLE
MSVCP140.dll missing

### ISSUE THREAD

**Issue by Gretsch** [powertab/powertabeditor#231]
On Win 64 bit PC - I had version 1.7
Then today found v 2.0 (thanks PowerTab is a great product),
but on install, got the MSVCP140.dll missing error message.

I rebooted and reinstalled, but still the same msg.

**Comment by cameronwhite** [comment]
Possibly related to #197 ?

**Comment by Gretsch** [comment]
read #197 
So uninstalled Audacity (left Ffmpeg and Lame)
Download installer from here: https://www.fosshub.com/Audacity.html/audacity-win-2.1.2.exe

The program started OK, but as soon as I tried to open a .ptb file - it gave the MSVCP140.dll missing msg.

Where can I get a valid version of the .dll?

**Comment by Gretsch** [comment]
In the absence of any suggestions:
I downloaded MSVCP140.dll from the MS site.
Now I get the error api-ms-win-runtime-l1-1-0.dll

Is it my PC, or are things missing from the v2 download?

**Comment by cameronwhite** [comment]
Sorry for the slow reply. Did you install the Visual Studio 2015 redistributable (e.g. http://stackoverflow.com/a/33274879), or something else? The PTE 2.0 installer should download and install that if it's not found on the system, though

**Comment by cameronwhite** [comment]
Closing unless there are further updates

**Comment by machtyn** [comment]
For the next person that has this problem and is still confused about what to do, follow these steps
1. Download the Visual C++ Redistributable for Visual Studio 2017
    a. 64-bit (Most users) http://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe
    b. 32-bit (If your system has less than 4GiB) http://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe
2. After you've downloaded the file, run it.
    a. Accept the license and click Next
    b. Click finish
3. Start Power Tab Editor (I'm assuming you've already installed it since you got the message and landed on this page.)

**Comment by blndev** [comment]
Your suggestion works well. But you should put this Information to the release page or at least close to the download link on the root page. 
Nearly nobody will search for closed issues. Specially is they are not interested in software development but only in music ;-)
