### ISSUE TITLE
Print song info

### ISSUE THREAD

**Issue by localchaos** [powertab/powertabeditor#232]
I could find no way to print the song info.  Windows 7, 64-bit.  Thanks.

**Comment by cameronwhite** [comment]
Duplicate of #49, I think

**Comment by localchaos** [comment]
Looks like this was first raised several years ago. Was it ever addressed? Maybe I'm not navigating the forum correctly but I don't see a fix, just a bunch of tags. Thanks. 

Sent from Yahoo Mail on Android 
 
  On Sat, Dec 10, 2016 at 9:24 PM, Cameron White<notifications@github.com> wrote:   
Duplicate of #49, I think

**Comment by cameronwhite** [comment]
No, it hasn't been implemented yet
