### ISSUE TITLE
Rests in Alpha 9 release

### ISSUE THREAD

**Issue by 3picF4ilFTW** [powertab/powertabeditor#233]
Hello there,

I hope this report does not exist already, I could not find it anywhere.

I just found out about this awesome program and immediately started using it. However, I ran into a bug. At first everything was workin fine, but suddenly one of the rests stopped working as intended. I tried to shrink the file to a minimal example which reproduces the problem.

The problem is the following:
I put a quarter rest right after an eigth note, however the note after the break was played an eight earlier, as if the rest actually was an eight rest. Attached you can find three files:
BugTest1: The pattern with an eight rest, this works as intended
BugTest2: The pattern with a  full rest (can also be a half rest whatsoever), this sounds exactly as BugTest1 although it should not
BugTest3: just like BugTest2, but also both patterns appended. Note that everything is working as expected with the latter 2, it is only the first rest that seems to be buggy.

As already stated, at first everything worked as it should, then i made some small adjustments somewhere else and it started showing the described behaviour. I even tried Ctrl-Z to roll back or load an old file, but it did not work. It still showed the same behaviour. Then I decided to reinstall the program, still the same problem.

Now, this was all happening in Alpha 9 for Win64.

I now installed Alpha8 for Win64 and everthing is working as expected, so I think that this bug was introduced between these two versions (if it actually is a bug which we will know as soon as you test it :D).

I hope that this is of any help to you.

[BugTest3.zip](https://github.com/powertab/powertabeditor/files/652527/BugTest3.zip)

EDIT: Forgot to mention it: I realized that it stopped working after adding a System, because after adding the System I was not ablo to hear anything. There was no sound playing. I used undo to roll back and that was when the mentioned bug occured. Just for your information, the minimal examples are made from scratch and are buggy for me nevertheless.

**Comment by cameronwhite** [comment]
Hmm, the second file plays back differently than the first for me (as expected). I'll give it a try on my Windows machine tomorrow, though

**Comment by cameronwhite** [comment]
For some reason those files don't even open successfully for me in alpha9 on Windows, but in the latest master build they're all opening and playing as expected. I think I'll close this, but please re-open if you run into it in a later alpha build
