### ISSUE TITLE
Error when opening pt2-files

### ISSUE THREAD

**Issue by milsen** [powertab/powertabeditor#234]
**Version:** (most recent) commit 99c33309
**OS:** Arch Linux

Whenever I try to open any Powertab 2.0-file (even empty ones or ones with just one note), I get this error message:
```
Error opening file: Parse error at offset 18446744073709551615: Missing a closing quotation mark in string.
```
where 18446744073709551615 is 2^64-1, the maximum unsigned 64 bit value. Powertab 1.7-files work fine.

It worked a couple of weeks ago, and since the powertabeditor code has barely changed in this time, the problem might have to do with one of the dependencies. My best guess is that the cause is either an update of qt5-base (to version 5.7.1-1) or boost (to version 1.62.0-4). Regarding boost, cmake gives me this warning multiple times when building:
```
CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106200
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  cmake/third_party/boost.cmake:14 (find_package)
  cmake/PTE_ThirdParty.cmake:5 (include)
  CMakeLists.txt:16 (include)
```
This could, however, also be unrelated.

**Comment by cameronwhite** [comment]
My guess would be a change in either boost (the zlib and iostreams libraries are used for decompressing the pt2 files), or in rapidjson - are you using your system's rapidjson package, or the one from the git submodule?

**Comment by milsen** [comment]
I am using my own system's rapidjson (1.1.0-1). Thanks for the hint, this fixed it for me now:
```
cd build/
rm CMakeCache.txt
cmake -DRAPIDJSON_INCLUDE_DIRS=~/pkg/powertabeditor/external/rapidjson/include/ ..
make -j4
```


Maybe it is because I know barely anything about cmake, but there are a couple of things that seem off about this. When trying to build from scratch it seemed like my rapidjson and rtmidi were not detected correctly (I had rapidjson-headers in `/usr/include/rapidjson` and rtmidi-headers in `/usr/include/rtmidi`):
```
-- Found rapidjson header files in /usr/include
...
-- Could NOT find rtmidi (missing:  RTMIDI_INCLUDE_DIR) 
-- Using RtMidi library from /home/milsen/pkg/powertabeditor/external/rtmidi
```

Lastly, using my own rapidjson with `cmake -DRAPIDJSON_INCLUDE_DIRS=/usr/include/rapidjson ..` did not solve the open-file-problem either - I had to use the git submodule instead.
Anyway, thanks for answering so quickly.

**Comment by cameronwhite** [comment]
I think it's looking for /usr/include/RtMidi.h based on comparing https://github.com/powertab/powertabeditor/blob/master/cmake/third_party/modules/Findrtmidi.cmake with https://github.com/powertab/powertabeditor/blob/master/cmake/third_party/modules/Findrapidjson.cmake. I don't remember if there was a reason I wrote it that way (Ubuntu's packages?), though
