### ISSUE TITLE
Double Clicking to open files - Windows 10.

### ISSUE THREAD

**Issue by Canaanabolaanan** [powertab/powertabeditor#236]
I have Alpha 10 open without any tabs loaded. If I open a folder of tabs external to the program, and double click to open a file there, quite often, it won't load, especially on the first attempt. I have associated this filetype with PT2, so that's not the issue. Further, I know the program recognizes the double click command as it flashes as though it recognizes it's taking priority, yet no tabs open. Sometimes it will load on the first attempt though. Seems to have about a 50% success rate. 

Related, if I right a file from the same folder and select "Open" from the menu, it has a 100% success rate. But again, I stress it's not the slowness of my double click. The program responds, but just doesn't load the file. It's as though it's checking to see that it's already open, confirms that it is, and so does nothing further. 

I remember seeing an email recently related to the responsiveness of toggling on/off the metronome. #185 I wonder if there's any connection due to the lack of proper response maybe in relation to the OS.

**Comment by cameronwhite** [comment]
I'll give this a try on Windows later - on OSX it seems to work fine.

**Comment by cameronwhite** [comment]
Yeah, I can reproduce this on Windows. It seems like the running application does get notified, but the list of files is empty for some reason.

**Comment by cameronwhite** [comment]
This should be fixed by 1f085e5!
