### ISSUE TITLE
Pause & Stop playback buttons don't respond if click release occurs after caret has moved

### ISSUE THREAD

**Issue by moppius** [powertab/powertabeditor#237]
When playing back a tab, if the user presses the left mouse button on the Stop button in the playback widget, but doesn't release the mouse button until the playback caret has moved, the Stop button will not perform any action.

If the left mouse button is pressed and released before the playback caret moves, it functions as expected.

**Comment by moppius** [comment]
It looks like whenever the caret moves, the Score Area gains focus, which steals focus from the button that the user started to click. You can see this by noticing the pixel border of the button loses its highlight as soon as the caret moves after the button is clicked.

This problem will manifest on any button since the Qt "clicked" action requires a press _and_ release event to occur _while the widget has focus_.

You can verify this by changing the `connectButtonToAction` method to `SIGNAL(pressed())` instead of `SIGNAL(clicked())`. This will now _always_ trigger correctly, but is not expected behaviour (e.g. you wouldn't be able to press and then move your mouse off the button and release to "cancel" the action).

It seems like the problem lies with the ScoreArea widget receiving focus every time the caret moves; it probably shouldn't, but I haven't figured out how to stop it from doing this yet :(

**Comment by cameronwhite** [comment]
Thanks for looking into this!
