### ISSUE TITLE
Trojan/Virus detected in Installer by Symantec Endpoint Protection

### ISSUE THREAD

**Issue by tcsmith11** [powertab/powertabeditor#240]
Specifically, powertabeditor-2.0.0-alpha10-win64.exe is detected as a Trojan.  I have not checked any other installers.

**Comment by cameronwhite** [comment]
Are there any diagnostics from your software about why it was flagged as a trojan?

**Comment by tcsmith11** [comment]
No, I sure don't.  It is being detected by Symantec's core/basic virus engine which is present across many of their products.  Later the installed executable also flagged as having a virus, so that might narrow down things a little.   Here's what I'm receiving so you can ask why it is being detected:

![symantec-zipfile](https://cloud.githubusercontent.com/assets/10701261/22390107/1e4c3b26-e4b7-11e6-993e-6bd41bb7649c.PNG)

![symantec-zipfile](https://cloud.githubusercontent.com/assets/10701261/22390120/37cbd5ac-e4b7-11e6-84ba-07d51ed54ca8.PNG)

**Comment by cameronwhite** [comment]
OK, I've filed a false positive report with Symantec

**Comment by cameronwhite** [comment]
Symantec verified the false positive, and said that the detection will be removed in the next update of virus definitions.

Thanks for reporting this!
