### ISSUE TITLE
Exported MIDI files cannot be played/opened

### ISSUE THREAD

**Issue by milsen** [powertab/powertabeditor#241]
I tried to export my Powertab files using "File"->"Save as..."->"Files of Type: MIDI File (*.mid)".
What I get are MIDI files that make rosegarden as well as ardour crash and timidity not play anything. However, I can play/use other MIDI files (created with hydrogen or rosegarden) just fine.

This happens regardless of what kind of Powertab file I try to export (empty, a couple notes, or very complex ones). The resulting MIDI files look like proper MIDI files at first sight and they do differ in size depending on the Powertab source. Timidity also does not report them as corrupted.

Here are the relevant parts of the outputs of  `timidity --verbose`, ardour and rosegarden.
```
Requested buffer size 32768, fragment size 8192
ALSA pcm 'default' set buffer size 33868, period size 3760 bytes
Playing s.mid
MIDI file: s.mid
Format: 0  Tracks: 0  Divisions: 0
2 supported events, 0 samples, time 0:00
No pre-resampling cache hit
Playing time: ~3 seconds
Notes cut: 0
Notes lost totally: 0
```

```
** (ardour-4.7.0:5399): CRITICAL **: SMF error: bad number of tracks: 0, must be greater than zero.
Segmentation fault (core dumped)
```

```
[Composition] Composition::getTrackById( 0 ) - WARNING - track id not found, this is probably a BUG  /build/rosegarden/src/rosegarden-16.06/src/base/Composition.cpp : 1653
[Composition] Composition::getTrackById( 0 ) - WARNING - track id not found, this is probably a BUG  /build/rosegarden/src/rosegarden-16.06/src/base/Composition.cpp : 1653
Segmentation fault (core dumped)
```
----
I just read [this helpful handout](http://www.ccarh.org/courses/253/handout/smf/#header_chunk). It seems that the first 8 bytes of the exported MIDI files are correct. Afterwards there are always 6 null-bytes, so the format, number of tracks and delta time units are not set, although they should be.

**Comment by cameronwhite** [comment]
I think I was able to (somehow) play them on Windows, but thanks for investigating this bug!

**Comment by rickyhan** [comment]
I have the same problem. On Linux it does not work somehow.

**Comment by misterperson** [comment]
I'm on Windows 10, and the issue exists. I have Synthesia and Anvil Studio installed and neither can open output files.
