### ISSUE TITLE
Error opening files from specific folders

### ISSUE THREAD

**Issue by Whitewolf2112** [powertab/powertabeditor#244]
I`m really digging the new version so far! Can`t wait to see the official non-beta release.

One small issue I found... I am able to open PT files from almost any folder of course, except if the folders' name has any symbols in it. Then I get the following error message:
**Error opening file: ios_base::failbit set: iostream stream error**
Not a big deal, just thought it was worth mentioning. Thanks.

**Comment by cameronwhite** [comment]
Do you have an example of those symbols? I'm guessing they're non-ASCII characters.

**Comment by Whitewolf2112** [comment]
Right. In this case specifically, I noticed it had trouble with my Queensrÿche folder. Of course, it works fine if I just change the "ÿ" to "y", but left as-is, there was never an issue with the old PT version.
As I said, just a small detail...
