### ISSUE TITLE
Make fails on Debian (jessie) x64

### ISSUE THREAD

**Issue by Grzyby** [powertab/powertabeditor#247]
After running 'make -j8' make fails with the errors: 

[ 76%] Building CXX object source/app/CMakeFiles/pteapp.dir/moc_command.cpp.o
[ 77%] Building CXX object source/app/CMakeFiles/pteapp.dir/tuningdictionary.cpp.o
[ 77%] Building CXX object source/app/CMakeFiles/pteapp.dir/moc_powertabeditor.cpp.o
/home/alex/Applications/PowerTabs/PTE2.0-fked/source/app/settings.cpp: In static member function ‘static QByteArray SettingValueConverter<QByteArray>::from(const SettingValue&)’:
/home/alex/Applications/PowerTabs/PTE2.0-fked/source/app/settings.cpp:89:9: error: ‘fromStdString’ is not a member of ‘QByteArray’
         QByteArray::fromStdString(boost::get<std::string>(v)));
         ^
/home/alex/Applications/PowerTabs/PTE2.0-fked/source/app/settings.cpp: In static member function ‘static SettingsTree::SettingValue SettingValueConverter<QByteArray>::to(const QByteArray&)’:
/home/alex/Applications/PowerTabs/PTE2.0-fked/source/app/settings.cpp:95:29: error: ‘class QByteArray’ has no member named ‘toStdString’
     return array.toBase64().toStdString();
                             ^
/home/alex/Applications/PowerTabs/PTE2.0-fked/source/app/settings.cpp: In static member function ‘static QByteArray SettingValueConverter<QByteArray>::from(const SettingValue&)’:
/home/alex/Applications/PowerTabs/PTE2.0-fked/source/app/settings.cpp:90:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/alex/Applications/PowerTabs/PTE2.0-fked/source/app/settings.cpp: In static member function ‘static SettingsTree::SettingValue SettingValueConverter<QByteArray>::to(const QByteArray&)’:
/home/alex/Applications/PowerTabs/PTE2.0-fked/source/app/settings.cpp:96:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
source/app/CMakeFiles/pteapp.dir/build.make:290: recipe for target 'source/app/CMakeFiles/pteapp.dir/settings.cpp.o' failed
make[2]: *** [source/app/CMakeFiles/pteapp.dir/settings.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:273: recipe for target 'source/app/CMakeFiles/pteapp.dir/all' failed
make[1]: *** [source/app/CMakeFiles/pteapp.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cameronwhite** [comment]
Which Qt version do you have? Qt 5.4 or higher is needed, I believe

**Comment by Grzyby** [comment]
Yes, that might be it, I only have Qt5.3. It looks like Qt5.4 is not yet available on Debian Jessie, do you know of any workarounds for this?

**Comment by cameronwhite** [comment]
I'm not sure, aside from building Qt from source or finding a PPA that provides Qt 5.4.
Just curious - if you do `make -k` to continue building, how many other errors are there with Qt 5.3? If it's not too many we could potentially insert some workarounds.

**Comment by cameronwhite** [comment]
I think this can be closed since it's related to an old Qt version.
