### ISSUE TITLE
Bad icon set

### ISSUE THREAD

**Issue by machtyn** [powertab/powertabeditor#248]
Windows 10 - 64 bit with 64 bit install. VS Studio Redist 2017
Why do the icons look like this:
![image](https://cloud.githubusercontent.com/assets/16729235/26384400/f7cb3852-4006-11e7-8cdd-0ef31df7de2f.png)

**Comment by cameronwhite** [comment]
It looks like the music notation font (Emmentaler) is messed up (or not being used). It should be using the one embedded in the exe, but maybe check your system's fonts in case there's anything weird there (like a font with the same name)

**Comment by machtyn** [comment]
I git cloned the project, copied the emmentaler from its location into the C:\Windows\Fonts folder and got the following error message: 
[Window Title]
Installing Fonts

[Main Instruction]
Cannot install emmentaler-13.otf

[Content]
The file 'C:\WINDOWS\Fonts\emmentaler-13.otf' does not appear to be a valid font.

[Close]

**Comment by machtyn** [comment]
Okay. It seems my wife, who likes to keep 30+ tabs open on her browser, and a dozen LibreOffice and pdf files open, was having some sort of problem with her computer. ... imagine that.  After a reboot and reattempt at installing the font, it worked fine and the program appears to be operating as expected.
