### ISSUE TITLE
README.md unclear for windows

### ISSUE THREAD

**Issue by QwertyZW** [powertab/powertabeditor#249]
>Use the "Add Entry" button to set the STRING CMAKE_PREFIX_PATH to the cmake directory inside Qt's installation directory (e.g. C:\Qt\5.4.1\lib\cmake)

>Press Configure and select your compiler version (e.g. Visual Studio 14 Win64, or Visual Studio 14 for a 32-bit build)  

> and then press Generate

>Open the resulting solution (powertabeditor.sln) and select Build Solution from the Build menu.

>Right-click on the powertabeditor project and select "Set as Startup Project" before running.

What is this GUI that is implied to be in use by those instructions? Is it visual studio?

**Comment by cameronwhite** [comment]
That's the CMake GUI - a couple instructions earlier it mentions installing and opening CMake

**Comment by QwertyZW** [comment]
ty
