### ISSUE TITLE
Compilation on Debian Stretch

### ISSUE THREAD

**Issue by sam81** [powertab/powertabeditor#255]
First of all kudos for this project. I've tried the alpha 10 version on Ubuntu using the ppa and I really like the feel of the old powertab revived and improved upon! I'm now trying to compile from source on Debian stable (Stretch) because that's my main OS, but the build fails. The output of the whole build process is available here:
https://gist.github.com/sam81/cff012eb34b0db9c98a26346ae25cfd3

I also ran the build with `make -k` the output is here:
https://gist.github.com/sam81/0ca1f2fc53fb65dc8804c3ec2c1db7ec

I ran `make -k >> output_log.txt` because the whole output didn't fit in the terminal window, however some messages were still printed in the terminal window, so I copied in the gist both those messages and the contents of `output_log.txt`

**Comment by cameronwhite** [comment]
From the first log it looks like it was using your system's installation of rtmidi (in /usr/include), so maybe check to verify that RtMidi.h is found there?

**Comment by sam81** [comment]
`RtMidi.h` was in `/usr/include/rtmidi/`, I made a symbolic link of both `RtMidi.h` and `rtmidi_c.h` (not sure this second one was needed) in `/usr/include` and the compilation went without issues, the program runs and the `pte_tests` pass.

**Comment by cameronwhite** [comment]
Glad to hear that worked! From https://github.com/powertab/powertabeditor/blob/master/cmake/third_party/modules/Findrtmidi.cmake, I would have expected /usr/include/rtmidi/RtMidi.h to be picked up, though

**Comment by sam81** [comment]
don't know what's the reason why it wasn't picked up before, I have no experience with C++, but I'm happy to test the compilation on Debian and report back any issues if you make changes to the code looking for the header file

**Comment by cameronwhite** [comment]
Could you give my latest commit a try?

**Comment by sam81** [comment]
just tried it, it works! I removed the symbolic links I had created to the header files before trying. The configuration step reports `-- Found rtmidi: /usr/include/rtmidi `, and the compilation succeeds without issue. I'm closing the issue.
