### ISSUE TITLE
Remove note shortcut not working in Mac

### ISSUE THREAD

**Issue by ttrahan** [powertab/powertabeditor#259]
Release: powertabeditor-2.0.0-alpha10-osx.app
OS: MacOS High Sierra 10.13.2

Deleting/removing a note works from the menu but not via the 'delete' key.

**Comment by cameronwhite** [comment]
I think Fn+Delete will work since that maps to the delete key sequence that Qt recognizes, instead of backspace.
Backspace isn't currently used for any shortcuts, so we could special case that for OSX so that the Delete key works as expected.

**Comment by ttrahan** [comment]
Thanks, Fn + Delete works.
