### ISSUE TITLE
debian stretch install failed

### ISSUE THREAD

**Issue by FunThomas424242** [powertab/powertabeditor#262]
I have cloned the 2.0.0-alpha10 tag and tried to build the project. But there is an error - what could be the cause? What is withershins?

```
huluvu424242@stachel:~/git/powertabeditor/build$ cmake ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
-- Found Catch: /usr/include  
-- Found pugixml: /usr/include  
-- Found rapidjson header files in /usr/include
-- Found ALSA: /usr/lib/x86_64-linux-gnu/libasound.so (found version "1.1.3") 
-- Found rtmidi: /usr/include  
-- Could NOT find withershins (missing:  WITHERSHINS_INCLUDE_DIR WITHERSHINS_LIBRARY) 
CMake Error at cmake/third_party/withershins.cmake:16 (add_subdirectory):
  The source directory

    /home/huluvu424242/git/powertabeditor/external/withershins

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  cmake/PTE_ThirdParty.cmake:11 (include)
  CMakeLists.txt:16 (include)


-- Using withershins library from /home/huluvu424242/git/powertabeditor/external/withershins
CMake Error at cmake/third_party/withershins.cmake:20 (set_target_properties):
  set_target_properties Can not find target to add properties to: withershins
Call Stack (most recent call first):
  cmake/PTE_ThirdParty.cmake:11 (include)
  CMakeLists.txt:16 (include)


CMake Error at cmake/third_party/withershins.cmake:26 (set_target_properties):
  set_target_properties Can not find target to add properties to: withershins
Call Stack (most recent call first):
  cmake/PTE_ThirdParty.cmake:11 (include)
  CMakeLists.txt:16 (include)


-- Found Git: /usr/bin/git (found version "2.11.0") 
-- Version number: 2.0.0-alpha10-0-ga06e5bfb
-- Configuring incomplete, errors occurred!
See also "/home/huluvu424242/git/powertabeditor/build/CMakeFiles/CMakeOutput.log".
```

**Comment by cameronwhite** [comment]
Did you do a recursive clone? That library should have been pulled in via a submodule

**Comment by FunThomas424242** [comment]
Thank you very much - no i dont had used the --recursive flag. Thank you for the hint. 

But now i have another error: 

`[ 55%] Building CXX object source/dialogs/CMakeFiles/ptedialogs.dir/moc_viewfilterdialog.cpp.o
/home/huluvu424242/git/powertabeditor/source/dialogs/fileinformationdialog.cpp: In constructor ‘FileInformationDialog::FileInformationDialog(QWidget*, const Document&)’:
/home/huluvu424242/git/powertabeditor/source/dialogs/fileinformationdialog.cpp:172:60: error: ‘const class QFileInfo’ has no member named ‘birthTime’
     ui->fileCreatedValue->setText(locale.toString(fileInfo.birthTime()));
                                                            ^~~~~~~~~
source/dialogs/CMakeFiles/ptedialogs.dir/build.make:498: die Regel für Ziel „source/dialogs/CMakeFiles/ptedialogs.dir/fileinformationdialog.cpp.o“ scheiterte
make[2]: *** [source/dialogs/CMakeFiles/ptedialogs.dir/fileinformationdialog.cpp.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet...
CMakeFiles/Makefile2:440: die Regel für Ziel „source/dialogs/CMakeFiles/ptedialogs.dir/all“ scheiterte
make[1]: *** [source/dialogs/CMakeFiles/ptedialogs.dir/all] Fehler 2
Makefile:138: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
`

**Comment by FunThomas424242** [comment]
Ok, sorry for remove my message, its was a mistake. 
Now i have used **git checkout 2.0.0-alpha10** after recursive clone but there are the following error:
`[ 38%] Built target ptewidgets
/home/huluvu424242/git/powertabeditor/source/audio/midioutputdevice.cpp:20:20: fatal error: RtMidi.h: Datei oder Verzeichnis nicht gefunden
 #include <RtMidi.h>
                    ^
compilation terminated.
source/audio/CMakeFiles/pteaudio.dir/build.make:66: die Regel für Ziel „source/audio/CMakeFiles/pteaudio.dir/midioutputdevice.cpp.o“ scheiterte
make[2]: *** [source/audio/CMakeFiles/pteaudio.dir/midioutputdevice.cpp.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet...
[ 63%] Built target ptedialogs
[ 73%] Built target pteformats
CMakeFiles/Makefile2:329: die Regel für Ziel „source/audio/CMakeFiles/pteaudio.dir/all“ scheiterte
make[1]: *** [source/audio/CMakeFiles/pteaudio.dir/all] Fehler 2
Makefile:160: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
`

Now i will be use the latest commit of master with **checkout master** and **git pull**.

**Comment by FunThomas424242** [comment]
Nice, the build is successfully done at commit 

> 01db3d8f306039d0c29847ca88f6a3a25d263157

Very thanks:

`[100%] Linking CXX executable ../bin/pte_tests
[100%] Built target pte_tests
huluvu424242@stachel:~/git/powertabeditor/build$ git log
commit 01db3d8f306039d0c29847ca88f6a3a25d263157
Author: Cameron White <cameronwhite91@gmail.com>
Date:   Sun Jun 3 15:47:14 2018 -0400

    Downgrade boost version
`

**Comment by cameronwhite** [comment]
Great!
