### ISSUE TITLE
Building Fails due to libbfd misconfiguration

### ISSUE THREAD

**Issue by gwwatkin** [powertab/powertabeditor#263]
On gentoo (`4.14.8-gentoo-r1`) the command:
`$ make -j4` 
 fails with this error:

`
[ 81%] Linking CXX executable ../../bin/powertabeditor
`
`
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../../lib64/libbfd.a(bfd.o): relocation R_X86_64_32S against symbol `bfd_errmsgs' can not be used when making a shared object; recompile with -fPIC
`

It tries to link it dinamically with a static library.
Changing in the `CMakeCache.txt`, generated by the `cmake ..` command in the build directory, the line:

`//Path to a library.`
`BFD_LIBRARY:FILEPATH=/usr/lib/libbfd.a `

to 
`
//Path to a library.`
`BFD_LIBRARY:FILEPATH=/usr/lib/libbfd.so
`

fixes the problem and every thing compiles fine.

Not sure how to fix it directly from the CMake configuration.

**Comment by cameronwhite** [comment]
The BFD library comes from https://github.com/cameronwhite/withershins/blob/master/cmake/FindBFD.cmake

**Comment by cameronwhite** [comment]
This should be obsolete with the latest commits, since we now use the boost stacktrace library and don't depend on libbfd
