### ISSUE TITLE
Dotted Notes not Displayed when Sharp or Flat

### ISSUE THREAD

**Issue by misterperson** [powertab/powertabeditor#265]
![image](https://user-images.githubusercontent.com/1425135/42246321-0f6fcc84-7ed1-11e8-9a58-b76477237aa7.png)

[The file in question](https://github.com/powertab/powertabeditor/files/2161194/DottedNotesLookWeird.zip)

Also, double dotted notes appear to be single dotted

**Comment by cameronwhite** [comment]
This was fixed for the alpha 11 release by #242
