### ISSUE TITLE
Turn sound off in playback

### ISSUE THREAD

**Issue by naneek** [powertab/powertabeditor#268]
Hi, for some reason I cannot seem to mute any of the instruments when the tab is playing. Is there some specific way to do this? I have treid using the mixer but nothing happens.

v2.0.0-alpha10-18-g82806330

**Comment by pdias94** [comment]
I can't mute any instrument at all... I want to listen only guitars but it does not work :(

**Comment by cameronwhite** [comment]
I think this is a duplicate of #276 - I'll close this issue in favour of that one since it has more details on the issue
