### ISSUE TITLE
Tempo is not correct, and fluctuates constantly

### ISSUE THREAD

**Issue by DakenSG** [powertab/powertabeditor#269]
Hello,

New user, just downloaded the program. I'm happy to see that someone has tried to resurrect this program, but when I loaded some files into it that I obtained from Ultimate-Guitar, right away I noticed that the tempo was playing slower than normal. I played the same file side-by-side in the old PowerTab editor, and the tempo in the this version of PowerTab Editor 2.0 beta was noticeably slower by about 10 bpm (possibly more).

In addition to this, when transitioning from one measure to the next, I've noticed that if a slide from one note to another is in the notation that playback also slows down considerably when going through the notes with a slide on them.

If you'd like to compare what I'm hearing, here is the file I'm using as a reference:
https://tabs.ultimate-guitar.com/tab/explosions_in_the_sky/the_birth_and_death_of_the_day_power_1238908
(the link is at the bottom)

Thanks! I look forward to seeing more developments with this program!

**Comment by MHGBand** [comment]
I've had the same problem, however I can almost swear it's playing at half the speed especially when there's a slide. An almost odd fix I've accidentally found is to use 1.7 alongside it. Open 1.7 and make a tab with lots of rests and repeat it. Then play both simultaneously and it runs Alpha 10 at normal speed, as far as I can tell with the tabs I've tried.

**Comment by cameronwhite** [comment]
I think it should be significantly improved by 71e1502. Please give it a try if you're able to compile from source!
