### ISSUE TITLE
Install on Ubuntu 18.04...

### ISSUE THREAD

**Issue by jmjr** [powertab/powertabeditor#272]
doesn't work due to depency issues and PPA is not accepted either. I'm not a developper, thus I don't know how to deal with these problems. Can anyone help?

**Comment by cameronwhite** [comment]
Can you provide the errors you get when following the build instructions?

**Comment by jmjr** [comment]
There are some dependecy issues: (The error message is in German)

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 binutils-dev : Hängt ab von: binutils (= 2.30-20ubuntu2~18.04) aber 2.30-21ubuntu1~18.04 soll installiert werden
                Hängt ab von: libbinutils (= 2.30-20ubuntu2~18.04) aber 2.30-21ubuntu1~18.04 soll installiert werden
 libasound2-dev : Hängt ab von: libasound2 (= 1.1.3-5)
 librtaudio-dev : Hängt ab von: libjack-dev
                  Hängt ab von: libpulse-dev soll aber nicht installiert werden
 librtmidi-dev : Hängt ab von: libjack-dev
 qtbase5-dev : Hängt ab von: libgl1-mesa-dev soll aber nicht installiert werden oder
                              libgl-dev
               Hängt ab von: libgles2-mesa-dev soll aber nicht installiert werden oder
                              libgles2-dev ist aber nicht installierbar
               Hängt ab von: libglu1-mesa-dev soll aber nicht installiert werden oder
                              libglu-dev
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.


Does that help?

**Comment by cameronwhite** [comment]
Sorry for the slow reply - I tried installing the list of packages from the README on an 18.04 system and didn't have any trouble. Maybe check if you have any custom settings / PPAs set up for your package manager?

**Comment by webdevilopers** [comment]
I currently have problems installing the PPA:
```
Please choose from the following available PPAs:
 * 'powertabeditor-stable':  Power Tab Editor stable builds
...
Err:9 http://ppa.launchpad.net/powertab-developers/powertabeditor-stable/ubuntu bionic Release                                              
  404  Not Found [IP: 91.189.95.83 80]
...
 E: The repository 'http://ppa.launchpad.net/powertab-developers/powertabeditor-stable/ubuntu bionic Release' does not have a Release file.
```

Any ideas? Thanks in advance!
