### ISSUE TITLE
Mixer does not seem functioning for panning/volume for each player

### ISSUE THREAD

**Issue by jairus-crabb** [powertab/powertabeditor#276]
Like title says, I have two players on different instruments and panning/volume changes seem to do nothing. I can't find anywhere else where this can be changed.

**Comment by jairus-crabb** [comment]
I also know a bit of C++, if this is a bug, I'd be happy to look into the issue myself if no one else knows what may be wrong of the top of their heads.

**Comment by cameronwhite** [comment]
Yeah I think this is a bug - there was a big refactor of how the midi playback was implemented, so I think this functionality was lost then. Patches are welcome!
Ultimately I think you need to end up calling `device.setChannelMaxVolume()` in the midi player. You might want to also fix `MidiFile` to properly record the source player / instrument for use in the midi player - there is some partial code already for that.

**Comment by mostafa-nabil** [comment]
I had a look at the issue and I did a quick fix for it locally. Hopefully I will deliver something soon.
My fix was mainly in MidiFile.cpp, but so far I did not need to use device.setChannelMaxVolume(). Still I will need more testing to do this

**Comment by cameronwhite** [comment]
Yeah, I think the original intention was to have volume changes take effect while playback is active (similar to changing playback speed or enabling / disabling the metronome)

**Comment by Ebdim9th** [comment]
Before the refactoring? the mixer was working on Alpha 8....

**Comment by cameronwhite** [comment]
This was fixed with #303

**Comment by Ebdim9th** [comment]
Do I do like before and download and install an updated version of Alpha 13 for this feature?

**Comment by cameronwhite** [comment]
Yeah, the installers from https://github.com/powertab/powertabeditor/actions/runs/376872326 will have the fix

**Comment by Ebdim9th** [comment]
thanks!

**Comment by Ebdim9th** [comment]
huh. installed, didnt make any difference. *headscratch*

**Comment by cameronwhite** [comment]
Hmm, adjusting the volume during playback works fine for me with those
installers (tested on macOS)

**Comment by Ebdim9th** [comment]
any ideas on what might be wrong with mine? Should i try to re-install? Hmmm I'll try that first....

**Comment by Ebdim9th** [comment]
The 'repair' relaunch worked perfectly! I didn't even have to temporarily shut down down Avast.... it balked a little but not enough to stop the re-install from completing.....

**Comment by Ebdim9th** [comment]
I got a new Dell w Windows 10, installed, I get that nifty dark theme choice but the volume pan "knobs" aren't working....

**Comment by cameronwhite** [comment]
Is the volume not working, the pan, or both? Offhand I'm not sure if the
pan will update live during playback

**Comment by Ebdim9th** [comment]
only the pan, the volume sliders work perfectly, i would test by panning hard left and right then dropping the volune of first one guitar then another to zero ...

**Comment by cameronwhite** [comment]
Yeah, I tested now and the pan seems to be ignored .. The volume slider works fine
Reopening this issue.

**Comment by Ebdim9th** [comment]
Thanks man! I really appreciate it... seriously. This is the /only/ tab program where i can go and not only be heard but find my requests pretty promptly and successfully implemented.
