### ISSUE TITLE
Request:  How to install on Windows

### ISSUE THREAD

**Issue by GretchPlayer** [powertab/powertabeditor#277]
1.7 has/is a great product, and I'm sure 2.0 is even better, but I'm a musician (not a software developer) and has never been able to install it  ;-)

I'm used to download in zip file containing a 'setup.exe' file, but 2.0 doesn't seem to have one.
Is there a simple way/guide to install on win?

**Comment by cameronwhite** [comment]
There are some installers available on the downloads page (https://github.com/powertab/powertabeditor/releases) under the "Assets" section

**Comment by GretchPlayer** [comment]
Hi Cameron,

 

Thanks for your email.

I tried the win-64 installer.

It said it needed to be 'repaired'! - I said yes, it opened powertab 2.00.

But on closure of the program, I triad to invoke it again, and it doesn't seem to have been installed.

 

Is there a 'support'forum I should use?

Regards ... Barry

{please excuse us of an alternative email address}

**Comment by cameronwhite** [comment]
I'm not sure - I just tried on a fairly fresh Win10 installation and it installed successfully for me
