### ISSUE TITLE
Compilation on Ubuntu 20.04

### ISSUE THREAD

**Issue by sam81** [powertab/powertabeditor#282]
I'm trying to compile on Ubuntu 20.04 but I'm getting an error. This is the output of `cmake`:  [cmake_out.txt](https://github.com/powertab/powertabeditor/files/4575950/cmake_out.txt)

**Comment by cameronwhite** [comment]
Should be fixed now! Don't forget to also pull in the update to the git submodules

**Comment by sam81** [comment]
thanks, that worked and the `cmake` step now goes smoothly [cmake_out2.txt](https://github.com/powertab/powertabeditor/files/4579710/cmake_out2.txt). However, I get an error later in the compilation process:

/home/sam/bin/powertabeditor/source/app/documentmanager.cpp: In member function ‘void Document::validateViewOptions()’:
/home/sam/bin/powertabeditor/source/app/documentmanager.cpp:174:41: warning: comparison of integer expressions of different signedness: ‘const int’ and ‘boost::iterator_range_detail::iterator_range_base<__gnu_cxx::__normal_iterator<ViewFilter*, std::vector<ViewFilter> >, boost::iterators::incrementable_traversal_tag>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  174 |              *myViewOptions.getFilter() >= myScore.getViewFilters().size())
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 78%] Building CXX object source/app/CMakeFiles/pteapp.dir/tuningdictionary.cpp.o
[ 78%] Building CXX object source/app/CMakeFiles/pteapp.dir/viewoptions.cpp.o
[ 78%] Building CXX object source/app/CMakeFiles/pteapp.dir/moc_command.cpp.o
[ 79%] Building CXX object source/app/CMakeFiles/pteapp.dir/moc_powertabeditor.cpp.o
[ 79%] Building CXX object source/app/CMakeFiles/pteapp.dir/moc_recentfiles.cpp.o
[ 79%] Linking CXX static library libpteapp.a
[ 79%] Built target pteapp
source/build/CMakeFiles/powertabeditor.dir/build.make:162: *** il modello dell'obiettivo non contiene alcun "%".  Arresto.
make[1]: *** [CMakeFiles/Makefile2:798: source/build/CMakeFiles/powertabeditor.dir/all] Error 2
make[1]: *** Attesa per i processi non terminati....
test/CMakeFiles/pte_tests.dir/build.make:1469: *** il modello dell'obiettivo non contiene alcun "%".  Arresto.
make[1]: *** [CMakeFiles/Makefile2:889: test/CMakeFiles/pte_tests.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by cameronwhite** [comment]
OK, I think I've fixed the remaining issues!

**Comment by sam81** [comment]
thanks, unfortunately now I'm getting an error again at the `cmake` stage:

    -- Found rapidjson header files in /usr/include
    CMake Error at cmake/third_party/rtmidi.cmake:32 (set_target_properties):
      set_target_properties called with incorrect number of arguments.
    Call Stack (most recent call first):
      cmake/PTE_ThirdParty.cmake:10 (include)
      CMakeLists.txt:27 (include)

**Comment by cameronwhite** [comment]
Ah, I didn't hit that on my test machine since I didn't have rtmidi installed on my system. Should be fixed now!

**Comment by sam81** [comment]
fantastic, it compiled now and seems to be running fine! Thanks
