### ISSUE TITLE
Implement a dark theme for the score

### ISSUE THREAD

**Issue by cameronwhite** [powertab/powertabeditor#286]
Related to #284 (which was resolved by always using a white background), it would be nice to support a dark theme for the score view.

**Comment by mostafa-nabil** [comment]
hello, I have checked #284, and I think #286 is more of a generic feature for all OSs, not just just an issue for OSX like the previous bug, as mentioned in the label. Is that true or did I misunderstand something?
I would like to work on this feature. Are there certain colors to stick to for the score dark theme? And is there a preferred place to add the dark-theme-enabling option?

**Comment by cameronwhite** [comment]
This would be great to have someone work on!

My original thinking was to follow the application's color palette (https://doc.qt.io/qt-5/qguiapplication.html#palette) which https://doc.qt.io/qt-5/qpalette.html recommends using, since that would follow whatever the default color scheme is from the user's environment. The score uses some additional color shades, so it might need to use something like `QColor::darker()` to compute the additional shades relative to the background / foreground color.
That also would hopefully mean that the print functionality would use the correct style (white background) even if the user has a dark theme.

I don't know for sure if this is the best approach, but I think it's at least a good start to identify and fix all the hardcoded colours in the score rendering code. The `ScoreArea` class is the containing widget to start from (e.g. 99bdeb37 changed its background colour), but most of the work occurs in the `SystemRenderer` class and other files in the `source/painters` directory. Definitely let me know if you have any questions!

**Comment by cameronwhite** [comment]
A related bug I noticed is that time signatures and key signatures are not visible in the OSX dark mode, because they are drawn with white text (probably inheriting the default theme) over a white background, instead of switching to dark text.

**Comment by mostafa-nabil** [comment]
@cameronwhite 
I think we would need white _note_ images to use them to use them in dark mode, what do you think?
There would only be a small challenge of knowing whether the theme used by the system is dark or not.

**Comment by cameronwhite** [comment]
The music notes are all drawn from a font, so I think it's just a matter of choosing the right text colour when they're drawn (hopefully!)
