### ISSUE TITLE
Incorrect playback of complex alternate endings

### ISSUE THREAD

**Issue by cameronwhite** [powertab/powertabeditor#293]
In the attached file ([alternate_endings.zip](https://github.com/powertab/powertabeditor/files/4741289/alternate_endings.zip)) the second alternate ending doesn't return to the start bar for the third and fourth repeats.

`RepeatIndexer` doesn't seem to record the second repeat bar in the repeated section, so it's skipped during playback.

**Comment by nbrunett** [comment]
Is there any work being done on this? If not, I can start a PR with a little fix I have that makes the above example work.

**Comment by cameronwhite** [comment]
No, go ahead if you have some fixes!
