### ISSUE TITLE
Not asked to save new tab if pre-existing file opened in another tab

### ISSUE THREAD

**Issue by nbrunett** [powertab/powertabeditor#304]
**Description**
If I open a file from disk and have an unsaved tab open at the same time, clicking the unsaved tab's "x" while in the from-disk tab closes the unsaved tab without asking if I want to save. It doesn't matter if I open the file first and then make a new tab or make a new tab and then open a file.

**To Reproduce**
1. Launch PTE.
1. Create a new document.
1. Edit the new document.
1. Open an existing file from disk (I've specifically done this with a GP5 and PT2 file).
1. While in the opened file tab, click the "x" on the Untitled tab.
1. Untitled tab closes without the dialog asking if I want to save the modified file.

**Version**
I'm running in macOS 10.15.5 and Alpha 13 of PTE.

**Comment by cameronwhite** [comment]
Confirmed, I suspect it's checking whether the current document is modified, rather than the one that is actually being closed.
