### ISSUE TITLE
None of the new Alphas, 11, 12, or 13 will install... afraid I'm more of a user than....

### ISSUE THREAD

**Issue by Ebdim9th** [powertab/powertabeditor#305]
....a programmer. Pretty simple, I guess I thought Windows 7 could run them, it has run Guitar Pro 7.5, but maybe not. Is that the problem? (Windows 10 only for 11, 12, and 13?)

**Comment by cameronwhite** [comment]
This wasn't broken intentionally, but there were a lot of changes from alpha 10 to 11. Did the installer give you an error message?

**Comment by Ebdim9th** [comment]
It said the install failed and read that I should fix certain issues and try again. Here was the error log, which, yikes, is beyond me, currently
![Screenshot 2020-08-19 09 22 11](https://user-images.githubusercontent.com/55242755/90647410-e8fb9a00-e1fd-11ea-9d00-f5b02b9fed0d.png)

**Comment by Ebdim9th** [comment]
Wait, here's the whole text document...
[Power_Tab_Editor_20200819002258.log](https://github.com/powertab/powertabeditor/files/5097121/Power_Tab_Editor_20200819002258.log)

**Comment by cameronwhite** [comment]
Thanks! It looks like Microsoft might have updated the Visual C++ redist installer, so its hash no longer matches what our installer expects. This probably affects Windows 10 too, but you'd only encounter this if it wasn't already installed on your system by some other program.

If you manually install https://aka.ms/vs/16/release/vc_redist.x64.exe , are you able to successfully install powertab?

**Comment by Ebdim9th** [comment]
I don't think so, but I'm going to give it a try

**Comment by Ebdim9th** [comment]
Alpha 12 was a success, not 13, but I got an error log for that.... 
[Power_Tab_Editor_20200819132917 alpha 13.txt](https://github.com/powertab/powertabeditor/files/5098553/Power_Tab_Editor_20200819132917.alpha.13.txt)

**Comment by cameronwhite** [comment]
Great, glad version 12 worked!
I'm not as sure what's going on with the latest error - I'd perhaps try again after rebooting, if you hadn't rebooted after installing the vc_redist package?

**Comment by Ebdim9th** [comment]
another simple possibility I have overlooked... straining at gnats... swallowing camels... I'll do it as soon as I get home

**Comment by Ebdim9th** [comment]
sadly, the pipe still closes, no joy on Alpha 13.....

**Comment by cameronwhite** [comment]
Thanks, I'll do some more investigation ..

**Comment by greenkingfisher** [comment]
Same problem at install here, windows 10:
![image](https://user-images.githubusercontent.com/70600919/91891236-9227a300-ec88-11ea-89dd-026f1e40af0a.png)

**Comment by cameronwhite** [comment]
I think this should be fixed by the changes in 43ec269 - can you try the installer from https://github.com/powertab/powertabeditor/actions/runs/235216866 and see if that works?

**Comment by Ebdim9th** [comment]
Downloading now, gonna give it a go....

**Comment by Ebdim9th** [comment]
I cant download it, it keeps 'finishing' at 1 mb or below.

**Comment by Ebdim9th** [comment]
i got as far as 10 mb and it crashed/ "finished" again. The first time I did reach 11MB, but when I tried to extract it, it read that the folder now contained 0 bytes....

**Comment by Ebdim9th** [comment]
I got it downloaded, run,  didn't work. Same result as before.

**Comment by cameronwhite** [comment]
Hmm, this worked fine for me on my clean Windows 7 VM
Did you get the hash code error, or the other error?

**Comment by Ebdim9th** [comment]
same general fail notice about the pipe now closing with the link for the wrror log....

**Comment by Ebdim9th** [comment]
Here's a snip:

![Capture](https://user-images.githubusercontent.com/55242755/92006629-97c5cd00-ed0a-11ea-90a5-bcd6df5d6bd0.PNG)

**Comment by cameronwhite** [comment]
Any chance you have an antivirus that might be interfering? I think this could be the issue from https://github.com/wixtoolset/issues/issues/5658
For alpha 13 the installer was generated with an older version of Wix (3.11) which wouldn't have that fix

**Comment by Ebdim9th** [comment]
I saw the download link there, ill try it when i get home.....

**Comment by cameronwhite** [comment]
I think the installer itself will need to be rebuilt with a newer version of Wix, but thank you for helping track down the source of the problem!

**Comment by Ebdim9th** [comment]
Right on! Glad I could help.... Power Tab is too good of a program to not keep improving on... have to say, as bad as the Covid thing has been, it seems to have brought people together to kick projects they were working on into overdrive..... I discovered the nested tuplets while exploring it, and I have to say that was worth it....

**Comment by Ebdim9th** [comment]
and, yes I do have other programs like Guitar Pro 7.5 and TuxGuitar, but to me lacking nested tuplets is a glaring omission....

**Comment by Ebdim9th** [comment]
any update on the installer anti-virus workaround?

**Comment by Ebdim9th** [comment]
right on....

**Comment by Ebdim9th** [comment]
I have Visual Studio for classes but im still a code baby, toddler, or adolescent, not sure which, definitely not skilled enough to help with the installer build, though I'd like to, my experiences so far are very narrow and I've got a looot more to learn, even with many of the basics....

**Comment by cameronwhite** [comment]
Thanks, I don't think any extra assistance is needed for this though - just trying to figure out some issues that are only occurring on the Github build machines ..

**Comment by cameronwhite** [comment]
OK, could you try installing from https://github.com/powertab/powertabeditor/actions/runs/245255908?

**Comment by Ebdim9th** [comment]
Success! Whoohoo!
![Screenshot 2020-09-10 00 07 48](https://user-images.githubusercontent.com/55242755/92684198-8d9f6200-f2fa-11ea-8a4a-21642a5bc504.png)

**Comment by Ebdim9th** [comment]
Oh... Avast still gave me a little trouble in the install but then it does that whenever I try to run projects in Visual Studio. But when I closed and re-opened the installed program, so far no troubles or hiccups like that...

**Comment by cameronwhite** [comment]
Great, thanks for confirming!

**Comment by DonLiborio** [comment]
I'm having the same problem ("The hash value is not correct" when the installer tries to install the C++ redistributable) but I can't find any files at https://github.com/powertab/powertabeditor/actions/runs/245255908.

**Comment by UglyHobbitFeet** [comment]
I'm on Windows 10 and getting the issue '0x80091007 - The Has Value is not correct'' with Alpha 12 and Alpha 13

**Comment by cameronwhite** [comment]
Thanks, glad you got it working with manually installing the redist.
I think it should be fixed with the latest builds (https://github.com/powertab/powertabeditor/actions) so we should probably do a new official release soon
