### ISSUE TITLE
[MAC OS] Pentagram change background color to white when Dark Theme enabled

### ISSUE THREAD

**Issue by GianniGM** [powertab/powertabeditor#307]
If we have Dark theme enabled in MacOs it shows up a dark background, it's quite complicated to read, would be nice as user to change the background to white when I'm in dark theme mode.

<img width="1792" alt="Screen Shot 2020-09-17 at 19 38 46" src="https://user-images.githubusercontent.com/5739601/93507088-71fd1280-f91d-11ea-805e-b552a03c7e61.png">

**Comment by cameronwhite** [comment]
We should probably add an option in the preferences for this.

**Comment by Ebdim9th** [comment]
Is this only for Mac? Id like to try a dark theme.....

**Comment by cameronwhite** [comment]
It follows the system theme's color palette currently and should work on other platforms depending on their theming capabilities (I think there was some testing done on Linux too)
I think the feature request here would be to add a preference for explicitly opting into a predefined light or dark theme, in addition to following the system default

**Comment by Ebdim9th** [comment]
I'll look around my OS and find to see if I can change that theme, I know there some general options but I'm not sure where to look specifically?

**Comment by Ebdim9th** [comment]
I couldn't find a setting to change a color theme on a program, not that isn't there, I just couldn't find it... I can do it with Visual Studio, but I think that is an option on start-up ehen I first log on to it.....

**Comment by cameronwhite** [comment]
Visual Studio does its own custom theming, I think.
For powertab this would just be controlled by whatever the system theme settings are in the control panel display options (I'm not on Windows right now so can't check if a suitable dark theme can be set up)

**Comment by Ebdim9th** [comment]
i couldn't find them there?  What should I look for? Im as slow moving as this reply.....

**Comment by GianniGM** [comment]
Yeah, I think an on/off toggle like "align theme with current system default" would be enough.
Another idea might be to revert pentagram colors.
I'm quite new to this project and I haven't written in C++ for quite a long time, but I can give it a try to find a solution for it.
