### ISSUE TITLE
PowerTab 2.0 is only available for x64 systems?

### ISSUE THREAD

**Issue by Audiohqt** [powertab/powertabeditor#310]
Hello

I found out about this project recently and was really positively surprised people are interested in fixing the problems of the best music composition tool out there, Still.

Simply because PT is so superbly lightweight, easy and most importantly fast to use, so you don't end up wasting valuable time for actual work.

Power Tab is perfect tool for people like me who have build studio system around old pro gear, which would be awfully expensive to replace, and pointless in the sense of production quality.

Sorry for rambling, but it's important for the point: I tried to install PT 2.0, but it seems to require x64 environment... which is pretty unfortunate. I might be able to port it to x86 myself, if I ever have time, (not in close foreseeable future), but I'd be interested if this is underway already.

If it isn't, it definitely should be.

Best regards, and thanks for this project!
Jacew

**Comment by cameronwhite** [comment]
I had dropped the 32-bit builds a while back, but it (hopefully) wouldn't be too hard to re-introduce now that the installers are [built automatically](https://github.com/powertab/powertabeditor/blob/master/.github/workflows/build.yml).

Assuming you're on Windows, you could try the installer from https://github.com/powertab/powertabeditor/releases/tag/2.0.0-alpha10 which was the last 32-bit version that was built

**Comment by cameronwhite** [comment]
This should be fixed now - can you try out the windows-x86 installer from https://github.com/powertab/powertabeditor/actions/runs/299604747?
