### ISSUE TITLE
Stopping MIDI playback, then starting up, still doesn't play bends again, unless....

### ISSUE THREAD

**Issue by Ebdim9th** [powertab/powertabeditor#311]
On Alpha 13, like the previous versions, when I stop MIDI playback, then pick up there, whether pausing to do something else or make adjustments in the tab, it doesn't acknowledge bends, though it does vibrato, unless I go back to the beginning and play the whole composition over again. Which, if I'm adjusting a bend, then listening to see if I got it right, is a bit of an inconvenience.

**Comment by cameronwhite** [comment]
This doesn't seem to be the case for me on macOS, but I'll need to test on some other platforms since this could be platform-specific

**Comment by Ebdim9th** [comment]
Thanks! It's an odd little glitch....

**Comment by cameronwhite** [comment]
Thanks! I could reproduce it on Windows
Should be fixed now, and you can try out the build from https://github.com/powertab/powertabeditor/actions/runs/300948687 once it's completed.

**Comment by Ebdim9th** [comment]
right on....

**Comment by Ebdim9th** [comment]
Avast is blocking it.

**Comment by Ebdim9th** [comment]
In fact it gave this spiel about interrogating the file, have no idea when I'll see it again, tells me I may not have permission... got a suggestion for a better antivirus program? I've about had it with Avast for a variety of reasons......

**Comment by cameronwhite** [comment]
I'm primarily on other platforms so I probably can't give a good recommendation, but on my Windows test machine I just have Windows Defender

**Comment by Ebdim9th** [comment]
Defender isn't very effective compared to Avast when Avast works like it's supposed to....

**Comment by Ebdim9th** [comment]
I disabled Avast's shields temporarily to install it, gonna restart to see if Avast leaves the program alone. (right now it's playing the bends wherever I stop at.)

**Comment by Ebdim9th** [comment]
Now I can't tell if Avast's shields are back up... shutting up now......

**Comment by Ebdim9th** [comment]
Everything has worked out..... 🎸
