### ISSUE TITLE
printing does not properly handle longer documents

### ISSUE THREAD

**Issue by DustanBower** [powertab/powertabeditor#313]
On my machine (Linux 5.8.11-1-MANJARO, powertabeditor-2.0.0-alpha12), I attempted to print a 3 page tab file.  It printed as a one-page tab file with very, very small print.  I was unable to find any configuration option to alter this layout and ultimately had to resort to printing to a pdf, opening it up in gimp, increasing the print size (possibly unnecessary), cutting it into 3 different layers, reexporting as a pdf, and printing from there.

Prior to that I tried setting a custom layout and increasing the width by 300%, which mostly corrected the size problem but would only result in page 1 being printed.  If the height and width weren't both increased by 300%, it had no effect on the print size.  The layout looked the same in print preview as well, so it was not simply a printer issue.

**Comment by cameronwhite** [comment]
Thanks for the report!
I tried testing on a couple different environments (macOS and Ubuntu 20.04) and multi-page printing to a PDF was working, although the title / subtitle text at the top was jumbled which is a separate bug. My initial thoughts are that either there's something odd with your tab file (although I wouldn't expect that to be the case) or there's something platform-specific going wrong (more likely)

- Which desktop environment are you using? (KDE, Gnome, etc)
- Would you be able to attach a simple example tab and the resulting pdf?

**Comment by DustanBower** [comment]
I'm using i3.  I just decided to test it by loading up powertab editor and adding 25 new sections and trying to print and I got the same effect.

[powertab-issue.zip](https://github.com/powertab/powertabeditor/files/5433967/powertab-issue.zip)

**Comment by cameronwhite** [comment]
Thanks for the example! The issue seems to be from having a completely empty score info section at the top (no title / subtitle etc) which wasn't the case for the files I was testing
