### ISSUE TITLE
Edit text

### ISSUE THREAD

**Issue by BigHonkinDaddy** [powertab/powertabeditor#322]
How can I edit the lyrics (text above the stave)?  I can add, but can't find a way to edit the text... possible enhancement?

**Comment by cameronwhite** [comment]
There is some active work going on to make the text and other items easily editable (e.g. #192), so it should be fixed fairly soon. Currently I think you have to remove and then re-add the text, which is quite annoying.

**Comment by cameronwhite** [comment]
Fixed by 34a21ab0

**Comment by BigHonkinDaddy** [comment]
Fabulous!  Thank you!
