### ISSUE TITLE
Section Labels

### ISSUE THREAD

**Issue by BigHonkinDaddy** [powertab/powertabeditor#326]
Add and edit section labels, such as "Intro", "Chorus", "Bridge", "Outro", "Verse" and allow to reference these labels throughout the score.  In other words, I'd like to be able to label the chorus section as "Chorus" and then reference it between the verses when I want to direct the player to repeat the chorus.

**Comment by cameronwhite** [comment]
I'm not sure if I'm misunderstanding, but you can add section labels at a bar line with `Shift+R` (Music Symbols -> Rehearsal Sign in the menu). Is there any functionality missing from that?

(The recent change ec1006ec8 makes it easier to edit existing labels, similar to the recent changes for editing text items)

**Comment by BigHonkinDaddy** [comment]
ah.  no, you're not misunderstanding...that's exactly the functionality I was thinking of.  Once I label a section using the Rehearsal Sign, can I then refer to a rehearsal sign to direct the player to that section of the score?  BTW, really nice job on this software.

**Comment by cameronwhite** [comment]
Thanks, glad you're enjoying it!
The rehearsal signs are more for labeling / navigation than direction, if that makes sense. You can jump to them with the `Position -> Go To Rehearsal Sign` menu, and of course can mention them in a plain text item.
For directions there is `Music Symbols -> Musical Direction` which has the classic direction types like `To Coda`
