### ISSUE TITLE
option to have notes sound when entered

### ISSUE THREAD

**Issue by Ebdim9th** [powertab/powertabeditor#327]
I've always wanted to have the option to turn on a feature where the notes sound as you enter them. Say, whether its a whole note or a thirty-second note, a tone maybe at roughly an eighth note's length sounds out. And also, I've been looking for it but I can't find the issue post about adding back the whammy bar function/articulation...

**Comment by cameronwhite** [comment]
I think this would be the same as #47 ?
The whammy bar request is #8

**Comment by Ebdim9th** [comment]
Thanks, that's what I was looking for, I couldn't find them in the list ...
