### ISSUE TITLE
Help .... Can't complete the download of any version after Alpha 10 on Windows (64)

### ISSUE THREAD

**Issue by DIMARC0** [powertab/powertabeditor#330]
**Description**
When clicking on the installer it will begin loading, getting about a 1/5 of the way through the install bar, and then stalls and retries several more times stopping at the same place, until finally erroring out with a hash tag error. Had the same problem before and after a fresh Windows installation. Alpha 10 installs fine.

**To Reproduce**

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
Windows 10 (64)

**Comment by psyomn** [comment]
Hi there: I think I saw a similar issue here https://github.com/powertab/powertabeditor/discussions/317#discussioncomment-562967 ; maybe this can fix your issue if it's similar?

**Comment by DIMARC0** [comment]
> Hi there: I think I saw a similar issue here [#317 (comment)](https://github.com/powertab/powertabeditor/discussions/317#discussioncomment-562967) ; maybe this can fix your issue if it's similar?

Yep, that did it - VC_redist.x64
Thank You!
