### ISSUE TITLE
Error opening .ptb

### ISSUE THREAD

**Issue by ChrisMash** [powertab/powertabeditor#332]
First off, loving the mission behind this project, keep up the good work!

I was trying to open a .ptb file with Alpha 14, on macOS, but I get hit with "Error opening file: Invalid MIDI preset", though it opens fine in the original Powertab on Windows.

The .ptb was originally generated by importing a MIDI and it did have some errors due to some of the notes being lower than a guitar can handle (it replaced them with an open E on the 1st string), so not sure if that's part of the issue.

No big priority on fixing this from my point of view, but wanted to let you know I'd come across it!

The .ptb in question: [bopeebo.ptb.zip](https://github.com/powertab/powertabeditor/files/6604676/bopeebo.ptb.zip)

**Comment by cameronwhite** [comment]
Thanks for the report! It does seem like the file indeed had an invalid MIDI preset (255) being used. I've committed a fix that gets it to load

**Comment by cameronwhite** [comment]
Also, you can grab an updated build from https://github.com/powertab/powertabeditor/actions/runs/912538372 once it's finished

**Comment by ChrisMash** [comment]
Quick fix! Nice!
