### ISSUE TITLE
MIDI player ignores mixer volume

### ISSUE THREAD

**Issue by BigHonkinDaddy** [powertab/powertabeditor#335]
**Description**
When starting the MIDI player anywhere in the score except the very first position, it will ignore the volume setting in the mixer and plays at full volume.

**To Reproduce**
1. Set the mixer volume to something other than full volume (around half volume works well to hear the difference)
2. Place the cursor in the first position of the score.
3. Click"Play".
4. Note the volume level.
5. Click"Pause". (You can click "Stop" instead, but then you must also move the cursor to another location in the score other than the first position in order to reproduce the defect.)
6. Click"Play".
7. Notice the volume is at full volume even though the slider control on the mixer is still set lower.

**Version**
Windows 7.  Alpha 15 x86.

**Comment by cameronwhite** [comment]
Confirmed.
The volume does update correctly after step 7 if the slider is moved a bit, so it seems that the volume just isn't being initialized properly when starting playback later in the score.
