### ISSUE TITLE
Title, subtitle, and artist name take up nearly half of the first page when printing.

### ISSUE THREAD

**Issue by TVCJR** [powertab/powertabeditor#338]
**Description**
When printing a song file, the title, subtitle, and artist name are huge and take up nearly half of the first page. Originally reported in bug 313.

**To Reproduce**
Use the attached song file and go to step 5 or:
1. Create a new song file
2. Add some notes to the score
3. Set the title, subtitle and artist name via the File Information dialog
4. Save the file
5. Do a print preview

**Additional Info**
![image](https://user-images.githubusercontent.com/9748818/133300180-c1cd9af1-d711-4911-9646-a8c59b0aeb3a.png)
[BigTitlePrintBug.zip](https://github.com/powertab/powertabeditor/files/7163727/BigTitlePrintBug.zip)

**Version**
OS: Windows 10 Version 10.0.19043 Build 19043 (x64)
PT: Power Tab Editor 2.0 Beta  (v2.0.0-alpha15-0-gbbbcc535)

**Comment by cameronwhite** [comment]
Confirmed, it looks similar on macOS too.
It seems to be related to the length of the text - if e.g. the artist name is very long, then it gets scaled back down to a more reasonable size.
