### ISSUE TITLE
Won't install or crashes on new laptop, depending on  64x or 86x

### ISSUE THREAD

**Issue by Ebdim9th** [powertab/powertabeditor#339]
I'm trying unsuccessfully to install on a new laptop; this is what I get when it wont, the second is what I get when it will, depending on the version ,64x, 86x, but won't work when I try to change the tunings:

![Screenshot 2021-11-02 022835](https://user-images.githubusercontent.com/55242755/139925500-418fca49-4b76-439e-bd1c-fd0498126785.png)

![Screenshot 2021-11-02 022427](https://user-images.githubusercontent.com/55242755/139925521-29a3180a-a10b-411e-aa0c-cff2f79bd9d8.png)

Re-installing and repairing don't work.

**Comment by cameronwhite** [comment]
Thanks for the report! I'll have to test this out on a clean virtual machine, but it sounds like somehow the installer isn't also installing the correct Visual C++ runtime.
Does manually installing https://aka.ms/vs/16/release/vc_redist.x64.exe / https://aka.ms/vs/16/release/vc_redist.x86.exe get it working, possibly after a restart?

Also, to clarify: the x64 version doesn't load at all, and the x86 version does open but fails when changing a tuning?

**Comment by Ebdim9th** [comment]
thats it.... 

'Also, to clarify: the x64 version doesn't load at all, and the x86 version does open but fails when changing a tuning?'

**Comment by Ebdim9th** [comment]
sorry, i installed both C++ and then the 64x and 86x and still, when i click on the tuning, get the same unhandled exception message.....

**Comment by cameronwhite** [comment]
If they open but crash when changing tunings, I'm wondering if the tuning dictionary file is corrupt? This would be a file named `tunings.json`, which on Windows I think is under AppData/Roaming/powertabeditor or something like that
You could try removing / renaming that so that it isn't used by the program

**Comment by Ebdim9th** [comment]
but i wouldnt be able to change tunings or add strings? (also, ive redownloaded the programs a couple of times, so Im not sure that's it)

**Comment by cameronwhite** [comment]
That file just has a copy of the preset tunings (including any custom tunings you've saved), so that's why I'm wondering if an issue with that file causes the tuning dialog to fail to open. I'm just guessing, though
It's saved in a preferences directory so that's not affected by reinstalling the program

**Comment by Ebdim9th** [comment]
got it, not sure where to look for  AppData/Roaming/powertabeditor though ?

**Comment by cameronwhite** [comment]
Oh sorry, it's a hidden folder by default - https://www.howtogeek.com/318177/what-is-the-appdata-folder-in-windows/

**Comment by Ebdim9th** [comment]
cool, thanks! lol provided  i can do it right ...

**Comment by Ebdim9th** [comment]
lol its not there. no AppData folder under users.

**Comment by Ebdim9th** [comment]
i found it elsewhere, but it just keeps duplicating the tunings.json file after ive deleted it every time i reopen the program and then try to access tunings....

**Comment by cameronwhite** [comment]
Ok, that sounds like it probably isn't the issue, assuming the file has some text in it and isn't just empty?
The program will always create a copy of the tuning dictionary there which is why it reappears

**Comment by Ebdim9th** [comment]
Its no longer there/duplicating, but the program still crashes with that unhandled exception dialogue box every time i try to access the tunings...

**Comment by Ebdim9th** [comment]
I think the issue is windows security, which can't be shut off for ten minutes like Avast or Bitdefender. I tried it on another windows 7 computer, turned off Avast for 10 minutes and it installed just fine. But not all windows 10 machines react w a Windows security block, i dont know why, so it installs in those cases w an antivirus pause as well.

**Comment by cameronwhite** [comment]
I'm hoping this is addressed by the revamped Windows installer (1e78fa9bf5fd007eaefa77997d28c8dfb3a80442). Tested on a clean VM it does successfully install the MSVC runtime
The tuning dictionary -related crashes should be solved now with #342
