### ISSUE TITLE
Erroneous translation license

### ISSUE THREAD

**Issue by comradekingu** [powertab/powertabeditor#345]
https://hosted.weblate.org/projects/powertabeditor/powertabeditor/#information
GNU General Public License v3.0 **only** → GNU General Public License v3.0 **or later**
as per https://github.com/powertab/powertabeditor/search?q=any+later
in
https://hosted.weblate.org/powertabeditor/powertabeditor/

**Comment by cameronwhite** [comment]
Good catch, thanks! This is fixed now
