### ISSUE TITLE
Export to Guitar Pro format

### ISSUE THREAD

**Issue by cameronwhite** [powertab/powertabeditor#350]
This would be useful for exporting to other applications, websites etc which may not understand `.pt2` files.

The best approach is probably to create `.gp` (GP7) files, since this mirrors how the guitar pro importer works. (The importers for versions 3/4/5/6 parse the file and then convert to our internal representation of the GP7 data, which is then converted to a .pt2 `Score`)

**Comment by Ebdim9th** [comment]
Does ascii export relate to this coding wise or is that an entirely different job even though technically an export?

**Comment by cameronwhite** [comment]
Ascii export is fairly unrelated since it's exporting to a very different format

**Comment by Ebdim9th** [comment]
So for now its a one or the other proposition and exporting to GP would ve more useful as the GP file you end up w can export to ascii, though i do hope to see import/export of ascii too eventually
