### ISSUE TITLE
time signature box stays checked until changed

### ISSUE THREAD

**Issue by Ebdim9th** [powertab/powertabeditor#356]
This was my idea over on Discord:

"I unfortunately change time signatures more than i ought to, but i was thinking of having a manual only, or option to switch to manual only, of checking and unchecking the time signature visible box, it doesnt have to show in every measure, just appear automatically each time i change it without me having to recheck the box again"

**Comment by cameronwhite** [comment]
I agree, having the time signature visibility be auto-enabled when you make a change is probably a good idea.
