### ISSUE TITLE
MIDI Player improvements - Count-in Toggle switch

### ISSUE THREAD

**Issue by BigHonkinDaddy** [powertab/powertabeditor#358]
A toggle switch on the MIDI player that turns on/off the count-in would be a big time saver.  I frequently toggle this back and forth as I'm writing and rehearsing using PT.  To this, usually with a guitar in my lap, I need to grab the mouse, go to File, Preferences, click the Enable toggle box on the Count in Section, press okay. and then do it again when I'm ready to switch it back.

The toggle could be very similar to the metronome toggle button which is already on the MIDI player.

**Comment by cameronwhite** [comment]
Agreed, this probably makes sense as a button next to the metronome toggle
