### ISSUE TITLE
MIDI Player goes out of tune

### ISSUE THREAD

**Issue by BigHonkinDaddy** [powertab/powertabeditor#361]
Sometimes, after pausing, repositioning and restarting the midi player, its out of tune, sometimes a step higher, sometimes a step lower.  When this happens, the midi player remains out of tune until encountering a bend or slide at then adjusts itself back to the proper tuning.

**To Reproduce**
I will attempt to reproduce the behavior in a sample file and upload.  More to come....

**Version**
Windows 10, Alpha 16.

**Comment by cameronwhite** [comment]
`MidiOutputDevice::stopAllNotes()` should probably also reset the pitch wheel
Or, maybe `MidiFile::load` should also reset the pitch wheel at the same time as it sets the pitch bend range
