### ISSUE TITLE
A reordering of the tunings drop down menu

### ISSUE THREAD

**Issue by Ebdim9th** [powertab/powertabeditor#363]
I thought of something else over on Discord, to perhaps change the tuning drop down list to where Eb is the choice directly below E standard (and then D, down one step, then on in that order til the drop bottom string and open chord tunings)

**Comment by cameronwhite** [comment]
I think this just requires shuffling things around in the `tunings.json` file

**Comment by Ebdim9th** [comment]
Oh yeah, i figured it wouldn't be an overly complex change, just a more useful one.....
