### ISSUE TITLE
Make the JSON content of .pt2 files easier for other programs to use

### ISSUE THREAD

**Issue by cameronwhite** [powertab/powertabeditor#368]
There are at least a couple issues with how scores are serialized to JSON that make it harder for other programs to import
- enums are serialized as integers (0,1,2 etc) which are mysterious without looking at the C++ source
- bit flags (e.g. for `Position::SimpleProperty` are serialized as a string of 0s and 1s that is awkward to figure out and deal with

There may be other issues, so we should review the JSON contents to look for anything odd

**Comment by cameronwhite** [comment]
Somewhat, yeah - guitar pro is obviously far more widely supported so that's still quite important!

The main thing here is to make sure these file format changes are done before leaving alpha and having a beta or official 2.0 release, to minimize future file format changes

**Comment by Ebdim9th** [comment]
The more the merrier! When do you change the designation from Alpha to Beta?

**Comment by cameronwhite** [comment]
Probably once we've got all the important missing features from v1.7, e.g. rhythm slashes
