### ISSUE TITLE
alterations

### ISSUE THREAD

**Issue by sbonaime** [powertab/powertabeditor#370]
Hi,
Would it be possible to add the b6 alteration ? I want to write down this chord. D#sus(b6,b9)

Thanks

<img width="697" alt="Capture d’écran 2022-01-29 à 11 45 20" src="https://user-images.githubusercontent.com/750709/151658035-b6cac0be-02a2-450c-8d1b-7c938e8d950b.png">

**Comment by cameronwhite** [comment]
Yep, that's definitely less common but I think would be ok to add 👍

**Comment by Ebdim9th** [comment]
This looks cool, didn't know it was a limitation...
