### ISSUE TITLE
in midi playback notes on different tracks misaligned

### ISSUE THREAD

**Issue by Ebdim9th** [powertab/powertabeditor#372]
(Brought this up in Discord discussion) i noticed say i have a quarter note in one track and sixteenth notes in the next below i have to line the next quarter note right over its corresponding sixteenth note or, even w justifying the section, the midi playback gets offset and the notes set discordant to one another, and that may happen in some imports too

**Comment by cameronwhite** [comment]
I haven't been able to reproduce this.. attached is my attempt which sounds fine
[note_offsets.pt2.zip](https://github.com/powertab/powertabeditor/files/7999966/note_offsets.pt2.zip)

**Comment by cameronwhite** [comment]
I think this can be closed, unless there's an example file to reproduce it
