### ISSUE TITLE
how to set italian language?

### ISSUE THREAD

**Issue by p060477** [powertab/powertabeditor#385]
is there a way to set italian lang?
thxs so much for yr kind attention
cheers!
:)

**Comment by cameronwhite** [comment]
It should follow your system language settings - e.g. on macOS I tested by setting Spanish as my preferred language and that worked as expected

However, there currently aren't any strings translated into Italian (https://hosted.weblate.org/languages/it/powertabeditor/) so everything would be falling back to English instead.

**Comment by p060477** [comment]
thxs so much again for yr patience and attention
i'm running windows 10 home desktop 64 bit
and in the options of yr sw i do not find how to set the language...
and yes due to the lack of any strings translated i've the sw only in english language
but when they will be available  also the ita lang. how to set the language in the options?
thxs again and apologize my very few skills
cheers

**Comment by cameronwhite** [comment]
There aren't any options in the program currently to set the language - if your system is set to use Italian then the program will also use that (if translations are available)

**Comment by p060477** [comment]
thxs again, but if i try to portable it as you suggest in the other issue opened by me about portabilization,
then how to set the language...??...if this is able only when you install it..
thxs again
cheers

**Comment by cameronwhite** [comment]
It would still work the same way - whatever the system language is set to on the other computer would be used

**Comment by p060477** [comment]
thxs so much indeed
is there a way to be informed when there will be updates?
i do not find and option, usual is in the tab info, to check updates
i thxs you so much again
you have been very kind, usefull and patienceable

**Comment by cameronwhite** [comment]
There isn't yet an automated update notification within the software, but you can subscribe to notifications from Github about new releases (with the "Watch" button at the top right of the page)
