### ISSUE TITLE
Error initializing midi output device

### ISSUE THREAD

**Issue by mzryz** [powertab/powertabeditor#386]
**Description**
opening PTE says: Error initializing midi output device

**To Reproduce**
Open the program
Also checking preferences there is no midi output device to select

**Additional Info**
I made sure to install timidity, also pulseaudio-alsa and pipewire-alsa

**Version**
Manjaro (latest, rolling)
v2.0.0.0-alpha18-0-g1f2771b2

**Comment by cameronwhite** [comment]
Are you using the snap or flatpak package? Perhaps there's an issue related to sandboxing

**Comment by psyomn** [comment]
> I was surprised that power tab isn't in the AUR, neither is TuxGuitar for some reason either :)

I can probably write you a one-off `PKGBUILD` if you would be willing to trial it with me a little bit.  I'm on the discord community of this project if you want to message me directly. 

Depending on how well the above goes, I can see what kind of work it would take to actually have it officially in the AUR.

**Comment by psyomn** [comment]
```
pkgname=powertabeditor
pkgver=2.0.0
pkgrel=1
pkgdesc='powertab editor'
arch=('x86_64')
url='https://github.com/powertab/powertabeditor.git'
license=('GPL3')
source=("${pkgname}-${pkgver}::git+https://github.com/powertab/${pkgname}.git")
sha256sums=('SKIP')

makedepends=("cmake")
depends=("qt5-base" "boost" "boost-libs" "nlohmann-json" "rtmidi" "pugixml" "minizip" "alsa-lib" "timidity++")

MAKEFLAGS="-j$(nproc)"

prepare() {
    cd "$srcdir/$pkgname-$pkgver"
}

build() {
    cd "$srcdir/$pkgname-$pkgver"
    mkdir -p build
    cd build
    echo "will install in ${pkgdir}"
    cmake .. -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX="${pkgdir}/usr"
    make
}

package() {
    cd "$srcdir/$pkgname-$pkgver"
    cd build
    make install
}
```

Not the most elegant but for whoever else might want this.

**Comment by cameronwhite** [comment]
Nice! Would be great to get it into the AUR
