### ISSUE TITLE
Crash when double clicking on a bend

### ISSUE THREAD

**Issue by grigaror** [powertab/powertabeditor#390]
**Description**
Second time crashing when I double-click on the band

**Additional Info**
Segmentation fault 0# 0x00007FF6E2EA7208 in powertabeditor
 1# 0x00007FF6E2EA643B in powertabeditor
 2# 0x00007FF6E2EA7B6F in powertabeditor
 3# exp2f in ucrtbase
 4# 0x00007FF6E3063F19 in powertabeditor
 5# _C_specific_handler in VCRUNTIME140
 6# _chkstk in ntdll
 7# RtlRestoreContext in ntdll
 8# KiUserExceptionDispatcher in ntdll
 9# 0x00007FF6E300CAD0 in powertabeditor

**Version**
Power Tab Editor 2.0 Beta (v2.0.0-alpha18-0-g1f2771b2), Windows 11
![crash](https://user-images.githubusercontent.com/88487131/187397244-20a4b8b4-f5a2-4fd1-8274-c40ffba6460e.png)

**Comment by cameronwhite** [comment]
Confirmed, thanks for the report!
I think the crash happens when the cursor happens to also be on an empty string, like in your screenshot
