### ISSUE TITLE
Crash on "Multi-Bar Rest"

### ISSUE THREAD

**Issue by NalihznehC** [powertab/powertabeditor#391]
**Description**
Crash on "Multi-Bar Rest".

**To Reproduce**
Start the program; Click ctrl+N (new file); Click R (add rest); Click on the "Multi-Bar Rest" button; Crash.

**Additional Info**
*None*

**Version**
Windows 10; Power Tab Editor 2.0 Beta (v2.0.0-alpha18-0-g1f2771b2)

**Comment by cameronwhite** [comment]
Confirmed, I also get a "Can't add multi-bar rest to a non-empty measure" error if I try adding the multi-bar rest to a measure that appears empty
