### ISSUE TITLE
Slideouts are forced to connect to the next note

### ISSUE THREAD

**Issue by NalihznehC** [powertab/powertabeditor#393]
**Description**
Slideouts are forced to connect to the next note, sometimes it will be ugly or unexpected.

**To Reproduce**

1. Open Powertab editor;
2. Press "ctrl"+"N" to create a new file;
3. Press "9" to create a note; Click on "Slide Out Of Downwards (X \ )" ![image](https://user-images.githubusercontent.com/39670573/192622418-b8a29bd4-6bd9-47c2-923d-b333fe024512.png) shown in the left Toolbox;
Now it should look like this:
![image](https://user-images.githubusercontent.com/39670573/192622048-a825bba4-30c8-43cc-831a-df55811be7a2.png)
which is what I wanted, neat and beautiful. However,
4. Press "→" twice and "↓" once to locate the position of the next note; Press "2" to create the second note;
Now it will look like this:
![image](https://user-images.githubusercontent.com/39670573/192622781-7c0e4a96-cf9e-43cf-afbd-d3b995431b00.png)
which is not what I wanted.

**Additional Info**
These forced connections are especially ugly when two notes are separated by a barline.
For example,
![image](https://user-images.githubusercontent.com/39670573/192623514-e14f8c50-59df-4026-9522-bc9f9f856093.png)

**Version**
Power Tab Editor 2.0 Beta (v2.0.0-alpha18-0-g1f2771b2)

**Comment by cameronwhite** [comment]
Confirmed, it should only do this for shift/legato slides between nodes, but not for a slide out of the note

**Comment by NalihznehC** [comment]
Now the lines are good, but the positions of "_sl._" are still remained unfixed.
I personally do not care about this label, but maybe someone will care about it in the future. Therefore, @cameronwhite if you have spare time, please also fix the "_sl._" labels. Thank you!

**Comment by NalihznehC** [comment]
![image](https://user-images.githubusercontent.com/39670573/192966675-a55d4506-00b1-4c76-b91d-7086f169907a.png)


> Now the lines are good, but the positions of "_sl._" are still remained unfixed. I personally do not care about this label, but maybe someone will care about it in the future. Therefore, @cameronwhite if you have spare time, please also fix the "_sl._" labels. Thank you!

**Comment by cameronwhite** [comment]
Ah good catch, I somehow didn't notice that
