### ISSUE TITLE
Crash when "ctrl"+"↓"

### ISSUE THREAD

**Issue by NalihznehC** [powertab/powertabeditor#394]
**Description**
I clicked on "ctrl"+"↓" when selecting a string with a note on another string.

**To Reproduce**
1. Open Power Tab Editor.
2. Press "ctrl"+"N" to create new file.
3. Press "↓" to locate the note, then press "0" to create it:
![image](https://user-images.githubusercontent.com/39670573/192854902-2a7f843a-3797-4852-9914-97750ff265a4.png)
4. Press "↑" to change string:
![image](https://user-images.githubusercontent.com/39670573/192855018-a99be61f-daf9-4739-a20d-fc72dc7e0939.png)
5. Press "ctrl"+"↓" to crash:
![image](https://user-images.githubusercontent.com/39670573/192855257-5e2705f9-d2ed-4076-aa4b-dec838012f9b.png)
6. Click "Report Bug..."
7. Submit new issue.

**Additional Info**
Segmentation fault 0# 0x00007FF67CE67208 in powertabeditor
 1# 0x00007FF67CE6643B in powertabeditor
 2# 0x00007FF67CE67B6F in powertabeditor
 3# seh_filter_exe in ucrtbase
 4# 0x00007FF67D023F19 in powertabeditor
 5# _C_specific_handler in VCRUNTIME140
 6# _chkstk in ntdll
 7# RtlRaiseException in ntdll
 8# KiUserExceptionDispatcher in ntdll
 9# 0x00007FF67CFCCC76 in powertabeditor
10# 0x00007FF67CF0A25E in powertabeditor
11# 0x00007FF67CF0A1B5 in powertabeditor
12# QUndoStack::push in Qt5Widgets
13# 0x00007FF67CF0AEF0 in powertabeditor
14# 0x00007FF67CE910E1 in powertabeditor
15# QObject::qt_static_metacall in Qt5Core
16# QAction::activate in Qt5Widgets
17# QAction::event in Qt5Widgets
18# QApplicationPrivate::notify_helper in Qt5Widgets
19# QApplication::notify in Qt5Widgets
20# QCoreApplication::notifyInternal2 in Qt5Core
21# QShortcutMap::dispatchEvent in Qt5Gui
22# QShortcutMap::tryShortcut in Qt5Gui
23# QWindowSystemInterface::handleShortcutEvent in Qt5Gui
24# QGuiApplicationPrivate::processKeyEvent in Qt5Gui
25# QWindowSystemInterface::sendWindowSystemEvents in Qt5Gui
26# QEventDispatcherWin32::processEvents in Qt5Core
27# qt_plugin_query_metadata in qwindows
28# QEventLoop::exec in Qt5Core
29# QCoreApplication::exec in Qt5Core
30# 0x00007FF67CE68D66 in powertabeditor
31# 0x00007FF67D00A187 in powertabeditor
32# 0x00007FF67D0088CA in powertabeditor
33# BaseThreadInitThunk in KERNEL32
34# RtlUserThreadStart in ntdll

**Version**
Windows 10 21H2
Power Tab Editor 2.0 Beta (v2.0.0-alpha18-0-g1f2771b2)

**Comment by NalihznehC** [comment]
I frequently saved this time, so I only lost 20 seconds of my work. I am less sad than the previous time.

**Comment by cameronwhite** [comment]
by the way, you can also grab the latest builds from the "Actions" page (e.g. https://github.com/powertab/powertabeditor/actions/runs/3147195343, once it's ready) to get all of the most recent fixes

**Comment by NalihznehC** [comment]
> by the way, you can also grab the latest builds from the "Actions" page (e.g. https://github.com/powertab/powertabeditor/actions/runs/3147195343, once it's ready) to get all of the most recent fixes

Thank you so much!
