### ISSUE TITLE
Add chord diagram 

### ISSUE THREAD

**Issue by sbonaime** [powertab/powertabeditor#408]
WIth "Add chord diagram", when the "Top Fret" is bigger than 10, we can only see the 1 on the right of the window

Macos Ventura 12.6
PowerTab 2.0 Beta alpha 19 g48acb0b
<img width="356" alt="Capture d’écran 2022-11-16 à 22 14 27" src="https://user-images.githubusercontent.com/750709/202551359-786050b1-f4aa-461d-a58f-d1f6d9ba8161.png">

**Comment by cameronwhite** [comment]
Thanks for catching that! Should be an easy fix

**Comment by sbonaime** [comment]
And the Top Fret start at 2 not 1 !
