### ISSUE TITLE
Newest software plays faster and has the slides delay fixed but it craps out by the 3rd staff and slows down

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#412]
Any ideas on this one?  Also, I went to try to remove a barline by selecting it but the selection expands to select the entire section, why is that happening?

I'm pleased to see that the slide delay has been fixed as it was so annoying before but I can't have my power tab composition suddenly slow down by only the 3rd staff.

DId I make a huge mistake by grabbing the latest (the beta version).  I need to coach people on which version to download, can someone help me?

I guess I need to start the file over rather than import it and seee what happens.  I need to start over yet again.

I'll assume for now that the file has damage from an earilier version of version 2.0 for now

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by PellTheTabber1** [comment]
> I now realize that the delays are unpredictable.  I sometimes get them, sometimes not.  The timing of a piece needs to be dead on but it delays at barlines now.  Each time I run the same file, I get different behaviors.  Is there some 3rd party timer involved?

**Comment by cameronwhite** [comment]
Closing as this could not be reproduced
