### ISSUE TITLE
Can a modality be added or is it in there already to update the position at the moment I insert a number?

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#413]
**Description**
Describe the change or improvement that you'd like to see.

**Additional context**

I always have to hit the arrow key.

**Comment by cameronwhite** [comment]
I'm not sure I understand what this means - can you explain further what you mean by modality and what behaviour you're hoping to see?

**Comment by cameronwhite** [comment]
Closing since no further info was provided
