### ISSUE TITLE
If I make even one mistake, then edit it ,the system slows down at the point where the mistake was fixed.

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#414]
This is a huge issue, it measns I can never make a single mistake even if I edit the mistake out. 

I put in a note, then realized that I wanted to insert  a barline there but it now slows down at that point.  I used the insert key to insert the standard barline, it's no long the space bar as before.  If this helps solve the bug.

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment]
Closing as this could not be reproduced
