### ISSUE TITLE
Copy and Paste of Notes and Bars does not work, the selector is wrong and it drops the last thing selected

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#416]
![Bug](https://user-images.githubusercontent.com/11949191/205471584-0321a788-b68a-4c63-9281-6ff029789252.jpg)
**Description**
I tiried to select a barline and delete it but it selects all the stuff before it too.  This is a very serious issue and I would guess it needs to be fixed right away.  In the meantime, I have a suggestion for people to use as a workaround.  Simply select the bar and one note to the RIGHT of the bar and then reinsert the missing note after hitting the delete key.  This is a godsend of a solution that I've found as it's no longer a showstopper of a bug.

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment]
I can reproduce this - selecting a bar line seems to sometimes inadvertently select all of the previous notes (the blue highlighted area), which is why they were then deleted
