### ISSUE TITLE
Polish score crashes

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#418]
**Description**
A description of what the bug is.

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment]
Can you please attach an example file that demonstrates the issue? Testing with a couple files, it didn't crash for me
