### ISSUE TITLE
Unable to edit 4th note on 4th string in a staff

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#419]
The software acts as if the 4th string is locked and cannot be edited.  I had to try to use Remove Space - even the Remove position didn't work.  I would say this is a MAJOR MAJOR issue in the software.  The note stays in the midi version of the piece even if shift backward is used as a desperate measure to get rid of the note.  Also, selecting an entire measure and then deleting does not delete all of the notes that were selected.  Another serious bug or design error.  I would classify these as Design errors.  In a proper design, such a bug would never happen in a million years.

Even if the entire measure is selected and Cut, the note on the 4th string at the second fret is left in the measure.  What????

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.  In a desperate attempt to remove the phantom note, I tried to use shift backward which removes it from the screen's GUI display but the note is still there inside the midi so it plays back.  This is a very serious bug, but it's now upgraded to a design issue!  If removing something from the screen doesn't also remove it from the system's file version, that's a serious problem of wrong and improper design!  Design flaw of a major caliber.

**Version**
The bug exists in all versions of Powertab on all versions of Windows for the last 10 years.  It needs to be fixed before doing anything else as it's a highly critical bug.  The menu items aren't enabled and disabled properly for one note in each section of the staff.  Is there some sort of counter?  Or are the files getting damaged?

**Comment by cameronwhite** [comment]
I cannot reproduce this and would need an example file where this occurs.
One thought is that the file is using multiple voices, in which case editing operations only apply to the current voice. you can switch between the 1st and second voice in the status bar below the score
