### ISSUE TITLE
The midi playback has improper delays all over.  It doesn't play back to the durations of the notes on the staff unless it's a version 1.7 file being played.

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#421]
**Description**
A description of what the bug is.

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment]
Can you provide an example file to reproduce this?

**Comment by cameronwhite** [comment]
Closing as this could not be reproduced
