### ISSUE TITLE
The midi playback doesn't deal with dotted notes in 2nd voice properly.

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#423]
I am forced to use a quarter note in pieces where the note SHOULD be a dotted quarter note.  Otherwise the note is delayed.  What should be 3/8 in time becomes 4/8 unlless the dot is removed from the note.  This is a major bug or design flaw.

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment]
Attached is an example file that plays back as expected for me.
Could you attach a file that demonstrates the problem for you?

[voices_dots.pt2.zip](https://github.com/powertab/powertabeditor/files/10325705/voices_dots.pt2.zip)

**Comment by cameronwhite** [comment]
Closing as this could not be reproduced
