### ISSUE TITLE
The system doesn't play back the last note of a measure - the midi simply leaves the note out.  End of  story!

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#424]
**Description**
A description of what the bug is.

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment]
Can you please attach an example file to reproduce the issue?

The attached file is a simple example that plays back correctly in my testing
[midi_playback.pt2.zip](https://github.com/powertab/powertabeditor/files/10329176/midi_playback.pt2.zip)

**Comment by PellTheTabber1** [comment]
> **Description** A description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the issue.
> 
> **Additional Info** If applicable, add a screenshot or attach an example file that demonstrates the issue.
> 
> **Version** If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using



> Can you please attach an example file to reproduce the issue?
> 
> The attached file is a simple example that plays back correctly in my testing [midi_playback.pt2.zip](https://github.com/powertab/powertabeditor/files/10329176/midi_playback.pt2.zip)

In words should be enough.  There are pieces of music where the music stops playing one note before that end, that's all.  The system needs logic to clean the scores up.  The scores become polluted in the files that store the information.  The reason this happens is that the system is not designed to avoid these problems from the start.  It's a design issue, not a simple bug.   The system is not adhering to standards of software design practice that store information separately from it's display.  The system should NEVER have skipped a note in a score.  I had to delte the note from the piece of music by working around it and simply eliminating that note from the piece which worked out ok.  The files containing the scores and midi become a mess - they storage needs to be resdesigned so it uses techiques of model view controller.  I know it doesn't use those techniques.  It needs to be rewritten a little bit to use Model View Controller techniques.  End of story.

**Comment by cameronwhite** [comment]
Sorry, but I cannot fix bugs that I can't reproduce. If you have a file that exhibits the issue, please attach that so I can investigate, but otherwise there's not much I can do.
