### ISSUE TITLE
Copy and Paste doesn't copy the barlines and only does one voice at a time

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#425]
**Description**
A description of what the bug is.

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment]
I think this is a duplicate of #125
