### ISSUE TITLE
I cannot find how to indicate either a brush of the strings or a strum - is there one of those or just use text?

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#430]
**Description**
A description of what the bug is.

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment]
There are a couple options:
- The "arpeggio up/down" option can indicate this, but it also affects midi playback (a slow strum through the notes of the chord)
- There's also the pick stroke up/down symbol to indicate direction. I thought there was also a feature request somewhere on here for adding a strum direction symbol that makes more sense for chords, but doesn't change midi playback like the arpeggio symbol does

**Comment by luzpaz** [comment]
Can this ticket be closed ?
