### ISSUE TITLE
Simply changed a note in the first measure of the piece from 5th string to 4th but 5th string note stays in the piece.  Why is the note staying in the piece.  Now what was 3 beats has 4 beats.  Crazy.

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#431]
It's as if you cannot edit any of your tablatures as the notes that were changed stay in the piece and they increase the duration.  The deletion of notes on the staff is not working correctly.  It has serious bugs.  It makes it awfully hard to use Powertab - it's too huge a bug to have.  It's not like it's wrong to edit a piece of tablature but we are getting punsihed - this bug has to be fixed.  What is corrupting the files?

Meanwhile, let it be known that I am forced to literally put place-holder notes in before removing a note.  This is the only workaround I've found so far.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment]
Please attach a simple example file or set of steps to reproduce the issue. In my testing I can shift notes between strings as expected
