### ISSUE TITLE
Is there a way to note the slight advance in time of a note - textural aspect rather than use 64th notes.  Also, since I have to use 64th, can 128th and 256th be added?

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#432]
**Description**
A description of what the bug is.

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment]
It sounds like a grace note is what you're looking for?
