### ISSUE TITLE
Changing a note to a grace note throws the whole 2nd voice completely off

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#433]
A simple change like changing a note into a grace note shouldn't throw the whole piece out of time.  It should only affect one note - the note, the grace note  itself.  Now I have to go through and artificially insert rests again.  The score looks like a piece of trash.  If the notes follow in time on the staff, then they shouldn't be played out of order.

How did the notes get out of order from where they are on the staff?  How can this happen?  Huge bug.

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment]
Please attach an example file that demonstrates the issue. MIDI playback of grace notes behaves as expected in my testing.
