### ISSUE TITLE
The grace notes are being displayed AFTER the note that follows them when it should be before.  Why? Bug.  

### ISSUE THREAD

**Issue by PellTheTabber1** [powertab/powertabeditor#434]
**Description**
A description of what the bug is.

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
If applicable, include your operating system (e.g. Windows 10) and which version of Power Tab Editor (e.g. Alpha 12) you are using

**Comment by cameronwhite** [comment]
I can't reproduce this issue. Could you please attach a simple example file that demonstrates the issue?
In my testing, notes maintain the same position when they are switched to a grace note

**Comment by PellTheTabber1** [comment]
The note plays in the correct order in midi which would be the voice 2 (more bass) note first in time, then the melody (treble).  But if you can just picture that the lower note in tone is to the RIGHT of the higher-note in tone.  I am not sure if this is correct or not, it just seems kind of weird and it's against how I sometimes do longer grace notes using a 1/64th note before the higher note on the staff.  The grace note is shown in the measure with the tail upwards and the note is drawn to the RIGHT of the note that follows it in time.  Just seems weird but the midi plays back in correct order.  It just seems weird that the midi plays the notes in an order different than they are on the staff.
