### ISSUE TITLE
Selecting File->Print Preview menu option specific tab causes powertabeditor to crash

### ISSUE THREAD

**Issue by shjuka** [powertab/powertabeditor#441]
**Description**
Selecting File->Print Preview on a specific powertab tab causes to power tab editor to crash on windows 11.

**To Reproduce**
1. Download 'Tommy Emmanuel - Questions.ptb'  powertab from Ultimate Guitar using this url  
https://tabs.ultimate-guitar.com/tab/tommy-emmanuel/questions-power-313770

2. Open Tab in Power Tab Editor
3. Click File->Print Preview

Expected result: Print Preview dialog shows up. 
Actual result: Debug Error message shows up
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Error!

Program: ...sers\shjuk\source\repos\powertabeditor\build\bin\Qt5Cored.dll
Module: 5.15.9
File: C:\dev\microsoft\vcpkg\buildtrees\qt5-base\src\5.15.9-142034631f.clean\src\widgets\graphicsview\qgraphicsscenebsptreeindex.cpp
Line: 227

ASSERT: "!item->d_ptr->itemDiscovered" in file C:\dev\microsoft\vcpkg\buildtrees\qt5-base\src\5.15.9-142034631f.clean\src\widgets\graphicsview\qgraphicsscenebsptreeindex.cpp, line 227

(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------
![powertab error](https://github.com/powertab/powertabeditor/assets/87152391/de5bd08d-03ae-4a0a-8245-af60b5861ebc)

**Additional Info**
[Tommy Emmanuel - Questions.zip](https://github.com/powertab/powertabeditor/files/11604414/Tommy.Emmanuel.-.Questions.zip)

Reproducible only in Debug version. In release version works fine.

**Version**
OS: Windows 11 Pro
OS Version:10.0.22621
Power Tab Editor:  2.0 Beta (v2.0.0-alpha19-21-g21e178b7)

**Comment by cameronwhite** [comment]
Thanks for reporting, confirmed on a Windows debug build. It looks like an assert from inside Qt code so this would only occur when using debug Qt libraries.
