### ISSUE TITLE
Opening .gpx error "invalid unordered_map<K, T> key"

### ISSUE THREAD

**Issue by Boston-of-Gilead** [powertab/powertabeditor#444]
**Description**
When I try to open a .gpx file I get the error "invalid unordered_map<K, T> key"

**To Reproduce**
.ptb, .gp, .gp5 open without issue.

Reinstall ineffective - confirmed that I did associate .gpx with the application.

File opens in Guitar Pro 7.6 without issue.

**Additional Info**
![image](https://github.com/powertab/powertabeditor/assets/26582745/f1d61752-848f-412b-9f05-71e85b9201f2)
![image](https://github.com/powertab/powertabeditor/assets/26582745/7547ad08-928d-4d25-b78b-530d05e79c40)

**Version**
PTE Alpha 19
Windows 10 x64 22H2 Build 19045.3208

**Comment by cameronwhite** [comment]
Thanks for the bug report!
This is likely an issue with the specific .gpx file - is it possible to attach or link to it? (it not, feel free to send it to me directly)

**Comment by Boston-of-Gilead** [comment]
> Thanks for the bug report! This is likely an issue with the specific .gpx file - is it possible to attach or link to it? (it not, feel free to send it to me directly)

Here's the link: https://tabs.ultimate-guitar.com/tab/christopher-cross/ride-like-the-wind-guitar-pro-1449593

Here is is open in Guitar Pro:

![image](https://github.com/powertab/powertabeditor/assets/26582745/1f3685f5-4c15-46ea-9b63-a47f3a73e8f9)

**Comment by Boston-of-Gilead** [comment]
Guessing unordered_map refers to https://github.com/powertab/powertabeditor/blob/e0e41a009099525d9f839e18dd057822ca52298e/source/formats/gpx/filesystem.h#L25 as every other instance of unordered_map I've seen wants either ints or musical letters (i.e. A-G) in that first result... neither of which would be a "K". 

I also tried:
Saving the file as .gp8 in GuitarPro (it doesn't offer me any other formats or an "All Files" option). Ineffective.
Running the Batch Converter on the file in GuitarPro. Ineffective.

**Comment by cameronwhite** [comment]
Thanks, I can reproduce with that file. It seems to be an issue with importing chords - as with #442 we've been finding that older `.gpx` files have some differences in their file formats

**Comment by cameronwhite** [comment]
Should be fixed with the latest build! (https://github.com/powertab/powertabeditor/actions/runs/5652004243)

**Comment by Boston-of-Gilead** [comment]
> Should be fixed with the latest build! 

Thanks!
