### ISSUE TITLE
Shortcut remapping not saving

### ISSUE THREAD

**Issue by pellens** [powertab/powertabeditor#447]
**Description**
When I change the shortcuts (Customize shortcuts), the next time I start up PTE, my changes are gone.

**To Reproduce**
1. Open PTE
2. Click File > Customize shortcuts
3. Change "Insert space" to ;
4. Adding a space with the key ; works
5. Save your work
6. Close PTE
7. Reopen PTE
8. Shortcut changes are gone

**Version**
2.0 beta

**Comment by cameronwhite** [comment]
Confirmed, not sure when this started failing.
Out of curiosity, which platform are you on? (The preferences are saved somewhat differently depending on the platform). I've only tested on macOS so far

**Comment by cameronwhite** [comment]
Fixed by ae699bbad79b5d95843d22645251db191e21a529

**Comment by pellens** [comment]
How can I get this update? :-)

**Comment by cameronwhite** [comment]
Installers are automatically built for each commit, which can be used to test changes before the next official release
e.g. https://github.com/powertab/powertabeditor/actions/runs/6215689093 (near the bottom of the page)
