### ISSUE TITLE
Barline Delete bug

### ISSUE THREAD

**Issue by BigHonkinDaddy** [powertab/powertabeditor#469]
**Description**
Can't delete a barline without deleting the entire contents of the of the System prior to the deleted barline position.

**To Reproduce**
1. add a bunch of notes followed by a barline, followed by a bunch of notes...
2. try to select the barline (either in the staff or in the tabs, both produce same result)
3. press the delete key or choose "Remove Position" from the Position menu
4. quickly press ctrl-z so you don't loose your work
5. save the file.

**Additional Info**

**Version**
Windows 10 22H2
Power Tab Editor 2.0 Beta  (v2.0.0-alpha19-0-g48acb0b)

**Comment by cameronwhite** [comment]
I wasn't able to reproduce this, but I'm not quite sure if I'm doing the same thing (undo / redo as in step 4 also works as expected)
Here's a quick video of how I was deleting the barline

https://github.com/powertab/powertabeditor/assets/303951/2b9cd9e4-684d-4a32-8afe-0eac89c86afb

**Comment by BigHonkinDaddy** [comment]
yeah, see, when I mouse over to and click on the barline exactly like what you did, the barline becomes highlighted AND all the preceding notes in the System are also selected - so of course, pressing delete at that time deletes the entire selection.  There's no way for me to select only the barline.  My work around is to insert a bogus note just prior to or just after the barline, then using the mouse I can select both the bogus note and the barline.  And then delete.

https://github.com/powertab/powertabeditor/assets/77425146/9373c84b-0038-4c8b-9ced-a418989161d8

**Comment by cameronwhite** [comment]
Ah, I think this was fixed already in #453, and I was testing on the latest dev build
I'd probably suggest installing a recent dev build from https://github.com/powertab/powertabeditor/actions, but you also might be able to work around it by using the arrow keys to move the caret to the bar line instead of clicking to select
