### ISSUE TITLE
Notes play as you enter them.

### ISSUE THREAD

**Issue by Canaanabolaanan** [powertab/powertabeditor#47]
Typing in a note into the notation produces a pitch immediately so that you may hear whether you're entering the correct note. This feature can be toggled on/off in preferences.

**Comment by jcelerier** [comment]
that would be a great feature indeed, any hope to get it ?

**Comment by cameronwhite** [comment]
I'll bump up the priority for this

**Comment by jcelerier** [comment]
if you guide me a bit through the source code I'd be interested in looking into it :-)

**Comment by cameronwhite** [comment]
Sure, that would be great!
The key presses are handled at https://github.com/powertab/powertabeditor/blob/97b66d353fa25fcedbd51b410b9dc40b0a0e0682/source/app/powertabeditor.cpp#L1878 

The normal MIDI playback is handled in a background thread through https://github.com/powertab/powertabeditor/blob/master/source/audio/midiplayer.cpp . I don't know if this functionality should necessarily go in there, but it might be a good starting point for a similar background thread that the app can send events to when notes are entered.

**Comment by jcelerier** [comment]
> The normal MIDI playback is handled in a background thread through https://github.com/powertab/powertabeditor/blob/master/source/audio/midiplayer.cpp . I don't know if this functionality should necessarily go in there, but it might be a good starting point for a similar background thread that the app can send events to when notes are entered.

wouldn't a good way be to have an event queue from the ui thread to the background midi thread sending "unattended" midi events to be played ?

**Comment by cameronwhite** [comment]
That sounds very reasonable, it would just need a few changes to keep the thread alive (currently a new one is spawned when playback starts) and handle different events in the background thread.

**Comment by Ebdim9th** [comment]
This is just what I was looking for. What's particularly interesting was I was playing back a GP3 file of an Animetal song and it got to an exaggerated whammy bar part and Power Tab's MIDI played it back perfectly even though it doesnt currently have that function in the tab symbols/effects drop down menu
