### ISSUE TITLE
"fine" crashes midi player

### ISSUE THREAD

**Issue by BigHonkinDaddy** [powertab/powertabeditor#470]
**Description**
The midi player crashes immediately after pressing "play" button on a score in which there's a musical direction for "fine".  There no error message.  It just closes the PowerTab.

**To Reproduce**
1. add a bunch of notes.
2. add a "fine" musical direction.  In my example, I also add Segno and Dal Segno al Fine to make sense of the direction - but the midi  crashes every time I play midi with "fine" somewhere in the score and never crashes when I remove fine.
3. play score with the midi player.

**Additional Info**
![image](https://github.com/powertab/powertabeditor/assets/77425146/31d18e95-15cb-425e-bdc3-f6bbd5b474f9)

**Version**
v2.0.0-alpha19-0-g48acb0b
Windows 10 home

https://github.com/powertab/powertabeditor/assets/77425146/659e4f07-6b08-4cdc-9d42-25a5efe9cafa

**Comment by cameronwhite** [comment]
Confirmed, thanks for reporting.
Attaching my simple file to reproduce:
[direction_bug.pt2.zip](https://github.com/powertab/powertabeditor/files/14733284/direction_bug.pt2.zip)
