### ISSUE TITLE
Build problem on Fedora 40

### ISSUE THREAD

**Issue by ycollet** [powertab/powertabeditor#478]
I am compiling the current git repository of powertab on Fedora 40 with gcc 14.1.1.
minizip-ng-compat-devel 3.0.10 is installed.
I needed to fix source/formats/gp7/gp7exporter.cpp to allow powertab to compile:
- adding '#include <zlib.h>' 
- renaming zipOpenNewFileInZip64 to zipOpenNewFileInZip_64
After that powertab compiled fine.

**Comment by cameronwhite** [comment]
Could you try the latest commit f6662dd and see if that works in your environment?

**Comment by ycollet** [comment]
Just check and it worked. Thanks a lot !
I close the ticket.
