### ISSUE TITLE
tie note over music bar

### ISSUE THREAD

**Issue by vollautomatisch** [powertab/powertabeditor#483]
Hi there

Does anybody know if this is possible in Power Tab Editor:
![pt](https://github.com/user-attachments/assets/2cf6e99c-1aa5-40e7-9076-616a2c8d983a)

Thank you

**Comment by cameronwhite** [comment]
I think you could  set it up with a tied note followed by the pulloff, like this example:
<img width="163" alt="notation" src="https://github.com/user-attachments/assets/afbfc143-30db-4b45-96ba-d45196b1e093">
