### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by vk8a8** [powertab/powertabeditor#485]
When playing my notated work, no audio comes out. System audio is working as normal with other applications.

OS: Arch Linux x86_64 6.10.6-arch1-1
Desktop: Kde Plasma (Wayland)
Audio: Pipewire 1.2.3-1
Version: Flatpak V2.0.0-alpha19

**Comment by cameronwhite** [comment]
I'd guess this is most likely MIDI-related - you could open the File -> Preferences window to check what MIDI devices and ports are on your system, and which one is being used. If you need a software synth, `timidity` is usually a good choice to install

**Comment by vk8a8** [comment]
Ihave timidity installed. Is there a way to hook up powertab to it? I cant figure it out

**Comment by cameronwhite** [comment]
It should appear in the list of MIDI ports in the `File` -> `Preferences` window under `MIDI Output Device`.
If you don't see anything related to timidity there, maybe the service isn't running? On Arch there might be some additional setup needed: https://wiki.archlinux.org/title/Timidity++#Daemon

**Comment by vk8a8** [comment]
I did miss the steps, but the Daemon doesn't want to start. It says that it doesn't exist?
`[vk8a8@stinkfart-81ca ~]$ sudo systemctl enable --now timidity.service`
`[sudo] password for vk8a8:`
`Failed to enable unit: Unit timidity.service does not exist`
`[vk8a8@stinkfart-81ca ~]$ sudo systemctl start timidity.service`
`Failed to start timidity.service: Unit timidity.service not found.`

**Comment by vk8a8** [comment]
after some discussion on the archlinux irc channel, i found out that i should've passed the --user flag to enable it for user instead of system, and ran systemctl not as root. like:
`$ systemctl enable --now --user timidity.service`
instead of
`$ sudo systemctl enable --now timidity.service`
thank you for your help.

**Comment by cameronwhite** [comment]
Thanks for the update! Great to hear it's working now
