### ISSUE TITLE
Perpetual crashes after changing key signature

### ISSUE THREAD

**Issue by karl-died** [powertab/powertabeditor#486]
**Description**
After changing the key signature of one file, I switched to a file in another tab and clicked on "Edit Key Signature...".
Usually the "Edit Key Signature..." menu item is greyed out, unless you click somewhere on the tab lines.
In this case the menu item was not greyed out, even though i hadn't selected anything, so when I clicked on "Edit Key Signature..." the program crashed. Now every time I try to open Power Tab Editor, it immediately crashes and throws the following error message:

```
Unhandled exception: Unknown object type. 0# main in /Applications/Power Tab Editor.app/Contents/MacOS/Power Tab Editor
 1# main in /Applications/Power Tab Editor.app/Contents/MacOS/Power Tab Editor
 2# std::__terminate(void (*)()) in /usr/lib/libc++abi.dylib
 3# __cxa_get_exception_ptr in /usr/lib/libc++abi.dylib
 4# __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) in /usr/lib/libc++abi.dylib
 5# SettingsTree::loadFromPlist() in /Applications/Power Tab Editor.app/Contents/MacOS/Power Tab Editor
 6# SettingsTree::loadFromPlist() in /Applications/Power Tab Editor.app/Contents/MacOS/Power Tab Editor
 7# SettingsManager::load(std::__1::__fs::filesystem::path const&) in /Applications/Power Tab Editor.app/Contents/MacOS/Power Tab Editor
 8# main in /Applications/Power Tab Editor.app/Contents/MacOS/Power Tab Editor
 9# start in /usr/lib/dyld
```

I even tried deleting and reinstalling the app, as well as deleting the "powertab" directory in "Application Support", but the programm still crashes and throws the same error.

**To Reproduce**
- Have 2 files open
- Edit the key signatue in one file
- Switch to the other file, that is in a state that usually would not allow you to edit the key signature
- Try to edit it anyway because the menu item isn't greyed out

**Version**
MacOS 15.0, Power Tab Editor Alpha 19

**Comment by karl-died** [comment]
I was able to reopen Power Tab Editor after deleting the /Library/Preferences/org.powertab.powertabeditor.plist file.

When replicating the bug, I got the following error message:
`Segmentation fault 0# main in /Applications/Power Tab Editor.app/Contents/MacOS/Power Tab Editor
 1# main in /Applications/Power Tab Editor.app/Contents/MacOS/Power Tab Editor
 2# _sigtramp in /usr/lib/system/libsystem_platform.dylib
 3# KeySignatureDialog::KeySignatureDialog(QWidget*, KeySignature const&) in /Applications/Power Tab Editor.app/Contents/MacOS/Power Tab Editor
 4# PowerTabEditor::editKeySignature() in /Applications/Power Tab Editor.app/Contents/MacOS/Power Tab Editor
 5# QMetaObject::activate(QObject*, QMetaObject const*, int, void**) in /Applications/Power Tab Editor.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
 6# QAction::activate(QAction::ActionEvent) in /Applications/Power Tab Editor.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
 7# QObject::event(QEvent*) in /Applications/Power Tab Editor.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
 8# QApplicationPrivate::notify_helper(QObject*, QEvent*) in /Applications/Power Tab Editor.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
 9# QApplication::notify(QObject*, QEvent*) in /Applications/Power Tab Editor.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
10# QCoreApplication::notifyInternal2(QObject*, QEvent*) in /Applications/Power Tab Editor.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
11# QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) in /Applications/Power Tab Editor.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
12# qt_plugin_instance in /Applications/Power Tab Editor.app/Contents/PlugIns/platforms/libqcocoa.dylib
13# qt_plugin_instance in /Applications/Power Tab Editor.app/Contents/PlugIns/platforms/libqcocoa.dylib
14# __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ in /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
15# __CFRunLoopDoSource0 in /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
16# __CFRunLoopDoSources0 in /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
17# __CFRunLoopRun in /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
18# CFRunLoopRunSpecific in /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
19# RunCurrentEventLoopInMode in /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
20# ReceiveNextEventCommon in /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
21# _BlockUntilNextEventMatchingListInModeWithFilter in /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
22# _DPSNextEvent in /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
23# -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] in /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
24# -[NSApplication run] in /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
25# qt_plugin_instance in /Applications/Power Tab Editor.app/Contents/PlugIns/platforms/libqcocoa.dylib
26# QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) in /Applications/Power Tab Editor.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
27# QCoreApplication::exec() in /Applications/Power Tab Editor.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
28# main in /Applications/Power Tab Editor.app/Contents/MacOS/Power Tab Editor
29# start in /usr/lib/dyld
`

**Comment by cameronwhite** [comment]
Confirmed, thanks for reporting!
