### ISSUE TITLE
Increase font size/zoom?

### ISSUE THREAD

**Issue by DigitallyRemastered** [powertab/powertabeditor#490]
**Description**
Would be nice to increase the font size or zoom on the view of the tablature.

**Additional context**
When I'm trying to read the tab and play guitar with some semblance of time without looking at my fretting hand, it would be very comfortable to read each number without much second guessing what string it should be on or which fret.

**Comment by cameronwhite** [comment]
There is a zoom option in the toolbar which can be used for this:

![zoom](https://github.com/user-attachments/assets/5a7b2ead-38a5-43e1-84c8-c7f6701e2017)
