### ISSUE TITLE
"Zoom" dropdown isn't wide enough.

### ISSUE THREAD

**Issue by BigHonkinDaddy** [powertab/powertabeditor#495]
**Description**
"Zoom" dropdown isn't wide enough.

**To Reproduce**
In PowerTabEditor, click on the zoom dropdown box's down-arrow and observe the values in the list are not visible.

**Additional Info**
<img width="610" alt="image" src="https://github.com/user-attachments/assets/cb6536ab-8c0b-4960-852b-24066fc51b75">

**Version**
<img width="362" alt="image" src="https://github.com/user-attachments/assets/76d2c3ac-e20c-4031-b611-978c34c967db">

**Comment by cameronwhite** [comment]
Thanks for the report! The labels aren't cut off like that on macOS so something different is happening on Windows, but increasing the width is probably the easiest fix
