### ISSUE TITLE
Barline can not be removed/deleted

### ISSUE THREAD

**Issue by BigHonkinDaddy** [powertab/powertabeditor#496]
**Description**
Barline can not be removed/deleted

**To Reproduce**
add a barline.  try to delete it. Delete key, backspace, ctrl-x, Edit.Cut, Edit.RemoveSelectedItem.

**Additional Info**
See video.

https://github.com/user-attachments/assets/970256b9-705f-4600-9e6f-5aeeaffcafe1

**Version**
<img width="362" alt="image" src="https://github.com/user-attachments/assets/162d0439-68f2-4fa5-a443-d8ab909cdacd">

**Comment by cameronwhite** [comment]
This is fixed now by 33935d81cb4120617a6f63c291e839fc8b929b4c - you can grab the build from https://github.com/powertab/powertabeditor/actions/runs/11830347087 to try it out

**Comment by BigHonkinDaddy** [comment]
Yep. It works!  Thanks!!!
