### ISSUE TITLE
"Speed" UI control is too narrow

### ISSUE THREAD

**Issue by BigHonkinDaddy** [powertab/powertabeditor#497]
**Description**
"Speed" UI control is too narrow

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
<img width="428" alt="image" src="https://github.com/user-attachments/assets/a7faa243-12fc-4915-a495-baed0ffa764b">

**Version**
![image](https://github.com/user-attachments/assets/0ff52380-a5ed-48bf-a83f-de386d68ba34)

**Comment by cameronwhite** [comment]
Looks similar to #495 so we probably just need to add more width to the widget, but it's surprising that it doesn't auto-expand

**Comment by cameronwhite** [comment]
There were some layout bugs with Qt's new Windows 11 theme, so for now I've reverted it to use the older theme (matching the alpha19 build)

**Comment by BigHonkinDaddy** [comment]
All is well now.  Thanks for the super quick turn around.
