### ISSUE TITLE
Loosing heads for first note of guitar and bass 

### ISSUE THREAD

**Issue by sbonaime** [powertab/powertabeditor#499]
Following #492 I still have issue with first note when I have a guitar and a bass. This time I have a player for each instrument and the problem is only for the first note.
2.0.20 on Macos
![bug](https://github.com/user-attachments/assets/716fb2cd-97f2-4ff4-aebe-8b0226630919)

**Comment by cameronwhite** [comment]
It looks like the Player Change is attached to the second position in the staff, not the first, so I think that would explain the similar issue to #492 for the first note. You'd need to delete it and then add a new Player change at the start of the score
