### ISSUE TITLE
Recent history/directory toolbar/pane. Windows 7 pinned/history.

### ISSUE THREAD

**Issue by Canaanabolaanan** [powertab/powertabeditor#52]
Couple of related ideas here. One is specifically for Windows and so maybe not a great concept for a cross platform app. The idea is to provide quick access to the tabs you've been working on lately with minimal effort. The 2nd image is from Tabledit (what I used before PTE.)

![windows 7 pinned](https://cloud.githubusercontent.com/assets/8230669/3716239/6e866378-1606-11e4-88b0-4879e3b14f89.png)

![tabledit - directory pane](https://cloud.githubusercontent.com/assets/8230669/3716240/72669620-1606-11e4-98b3-f5725d6507de.png)

**Comment by cameronwhite** [comment]
I'd say this is fixed - since ee987d3834d5ff1b0afa5b9bef92cccd8192fa41 the recent files are added to the taskbar jump list, and Windows allows pinning those.
Inside the program the recent files are also available from File -> Recent Files
