### ISSUE TITLE
Add support for tremolo. 

### ISSUE THREAD

**Issue by Canaanabolaanan** [powertab/powertabeditor#8]
![tremolo](https://cloud.githubusercontent.com/assets/8230669/3667812/5430f24c-120d-11e4-8c70-442537ed37f0.png)

**Comment by Ebdim9th** [comment]
What do you have to do coding-wise, not that I'd know how to apply it, to add the feature in?

**Comment by cameronwhite** [comment]
There's a decent amount of work - implementing midi support, rendering, the edit dialog, importing from various file formats, etc. It would be pretty similar to the steps for #17

**Comment by Ebdim9th** [comment]
I figured, looking at it, I hate being handicapped in that area,  I get into programming code, its not an uphill battle for me, its just that there's so much of it and I feel like the professors are wasting time in some parts, while soeeding through others....

**Comment by Ebdim9th** [comment]
For me, add the whammy bar function, and Power Tab would be functionally complete. I like the idea of notes sounding as tou enter them, but I don't need it.
