### ISSUE TITLE
Incomplete Import of GP and PTE 1.7 file

### ISSUE THREAD

**Issue by henkmosseveld** [powertab/powertabeditor#95]
I compared one of my transcriptions (Joe Bonamassa - Faux Mantini), because someone imported my transcription in GP and placed it on Ultimate @#*^$. I also imported my version from 1.7.
So 3 versions to compare, with the original in the middle.

The GP import has a 4/4 beaming pattern (instead of 8/8 = 3-3-2)
Chordnames and Text haven't been imported from GP.
Vibrato and Bends haven't been imported from GP.
Key Signature is only displayed on system 1 in GP.

But what wonders me most: both imports miss a 1/16 note on beat 5!!

![incomplete import of gp and pte 1 7](https://cloud.githubusercontent.com/assets/8604110/4125006/b38ee1b8-32dd-11e4-89e9-4961c8170634.PNG)

**Comment by cameronwhite** [comment]
I tested with the latest revision and the 16th note issue in the pictures has. been resolved.
Bends (f2ca1370c3d1b679f97adb42730044a9d17532d6) and vibrato (a1a7d5f327f3afc88885e725a6018463ddbd7e13) are also now imported (#30) and key signatures are also now correctly displayed at the start of each system.
